-- Fix ON DELETE rules on FKs to directus_users that block user deletion.
-- Generated by scripts/fix-user-fk-ondelete.ts from live schema introspection.
-- Idempotent + safe to re-run. For each (table,column) referencing a user:
--   * skips it if the column does not physically exist
--   * nulls orphan refs (or deletes the row for NOT NULL CASCADE targets)
--   * drops any existing FK and re-adds it with the correct ON DELETE rule
DO $mig$
DECLARE
  r record;
  n_clean bigint;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('appointments','user_created','appointments_user_created_foreign','SET NULL'),
    ('appointments','user_updated','appointments_user_updated_foreign','SET NULL'),
    ('ar_analytics','user_created','ar_analytics_user_created_foreign','SET NULL'),
    ('ar_analytics','user_updated','ar_analytics_user_updated_foreign','SET NULL'),
    ('ar_clients','user_created','ar_clients_user_created_foreign','SET NULL'),
    ('ar_clients','user_updated','ar_clients_user_updated_foreign','SET NULL'),
    ('availability','user_created','availability_user_created_foreign','SET NULL'),
    ('availability','user_updated','availability_user_updated_foreign','SET NULL'),
    ('before_and_afters','user_created','before_and_afters_user_created_foreign','SET NULL'),
    ('before_and_afters','user_updated','before_and_afters_user_updated_foreign','SET NULL'),
    ('block_callout','user_created','block_callout_user_created_foreign','SET NULL'),
    ('block_callout','user_updated','block_callout_user_updated_foreign','SET NULL'),
    ('block_item_slideshow','user_created','block_item_slideshow_user_created_foreign','SET NULL'),
    ('block_item_slideshow','user_updated','block_item_slideshow_user_updated_foreign','SET NULL'),
    ('block_items_slideshow','user_created','block_items_slideshow_user_created_foreign','SET NULL'),
    ('block_items_slideshow','user_updated','block_items_slideshow_user_updated_foreign','SET NULL'),
    ('block_masonry','user_created','block_masonry_user_created_foreign','SET NULL'),
    ('block_masonry','user_updated','block_masonry_user_updated_foreign','SET NULL'),
    ('block_parallax_grid','user_created','block_parallax_grid_user_created_foreign','SET NULL'),
    ('block_parallax_grid','user_updated','block_parallax_grid_user_updated_foreign','SET NULL'),
    ('block_reveal','user_created','block_reveal_user_created_foreign','SET NULL'),
    ('block_reveal','user_updated','block_reveal_user_updated_foreign','SET NULL'),
    ('block_sticky_text','user_created','block_sticky_text_user_created_foreign','SET NULL'),
    ('block_sticky_text','user_updated','block_sticky_text_user_updated_foreign','SET NULL'),
    ('blog','user_created','blog_user_created_foreign','SET NULL'),
    ('blog','user_updated','blog_user_updated_foreign','SET NULL'),
    ('business_hours','user_created','business_hours_user_created_foreign','SET NULL'),
    ('business_hours','user_updated','business_hours_user_updated_foreign','SET NULL'),
    ('call_logs','user_created','call_logs_user_created_foreign','SET NULL'),
    ('call_logs','user_updated','call_logs_user_updated_foreign','SET NULL'),
    ('call_routes','user_created','call_routes_user_created_foreign','SET NULL'),
    ('call_routes','user_updated','call_routes_user_updated_foreign','SET NULL'),
    ('capabilities','user_created','capabilities_user_created_foreign','SET NULL'),
    ('capabilities','user_updated','capabilities_user_updated_foreign','SET NULL'),
    ('case_studies','user_created','case_studies_user_created_foreign','SET NULL'),
    ('case_studies','user_updated','case_studies_user_updated_foreign','SET NULL'),
    ('cd_activities','user_created','cd_activities_user_created_foreign','SET NULL'),
    ('cd_contacts','user_created','cd_contacts_user_created_foreign','SET NULL'),
    ('cd_contacts','user_updated','cd_contacts_user_updated_foreign','SET NULL'),
    ('cd_xp_state','user_created','cd_xp_state_user_created_foreign','SET NULL'),
    ('channels','user_created','channels_user_created_foreign','SET NULL'),
    ('channels','user_updated','channels_user_updated_foreign','SET NULL'),
    ('client_portal_users','user','client_portal_users_user_foreign','CASCADE'),
    ('clients','user_created','clients_user_created_foreign','SET NULL'),
    ('comment_reports','user_created','comment_reports_user_created_foreign','SET NULL'),
    ('comments','user_created','comments_user_created_foreign','SET NULL'),
    ('comments','user_updated','comments_user_updated_foreign','SET NULL'),
    ('contacts','user_created','contacts_user_created_foreign','SET NULL'),
    ('contacts','user_updated','contacts_user_updated_foreign','SET NULL'),
    ('content_plans','approved_by','content_plans_approved_by_foreign','SET NULL'),
    ('content_plans','user_created','content_plans_user_created_foreign','SET NULL'),
    ('courses','user_created','courses_user_created_foreign','SET NULL'),
    ('courses','user_updated','courses_user_updated_foreign','SET NULL'),
    ('directus_activity','user','directus_activity_user_foreign','SET NULL'),
    ('directus_comments','user_updated','directus_comments_user_updated_foreign','SET NULL'),
    ('directus_files','modified_by','directus_files_modified_by_foreign','SET NULL'),
    ('directus_files','uploaded_by','directus_files_uploaded_by_foreign','SET NULL'),
    ('directus_notifications','sender','directus_notifications_sender_foreign','SET NULL'),
    ('directus_versions','user_updated','directus_versions_user_updated_foreign','SET NULL'),
    ('earnest_history','user_created','earnest_history_user_created_foreign','SET NULL'),
    ('earnest_reviews','user_created','earnest_reviews_user_created_foreign','SET NULL'),
    ('earnest_scores','user_created','earnest_scores_user_created_foreign','SET NULL'),
    ('email_partials','user_created','email_partials_user_created_foreign','SET NULL'),
    ('email_partials','user_updated','email_partials_user_updated_foreign','SET NULL'),
    ('email_templates','user_created','email_templates_user_created_foreign','SET NULL'),
    ('email_templates','user_updated','email_templates_user_updated_foreign','SET NULL'),
    ('emails','user_created','emails_user_created_foreign','SET NULL'),
    ('emails','user_updated','emails_user_updated_foreign','SET NULL'),
    ('heros','user_created','heros_user_created_foreign','SET NULL'),
    ('heros','user_updated','heros_user_updated_foreign','SET NULL'),
    ('industries','user_created','industries_user_created_foreign','SET NULL'),
    ('industries','user_updated','industries_user_updated_foreign','SET NULL'),
    ('invoices','user_created','invoices_user_created_foreign','SET NULL'),
    ('invoices','user_updated','invoices_user_updated_foreign','SET NULL'),
    ('lead_activities','user_created','lead_activities_user_created_foreign','SET NULL'),
    ('lead_activities','user_updated','lead_activities_user_updated_foreign','SET NULL'),
    ('leads','user_created','leads_user_created_foreign','SET NULL'),
    ('leads','user_updated','leads_user_updated_foreign','SET NULL'),
    ('line_items','user_created','line_items_user_created_foreign','SET NULL'),
    ('line_items','user_updated','line_items_user_updated_foreign','SET NULL'),
    ('mailing_lists','user_created','mailing_lists_user_created_foreign','SET NULL'),
    ('mailing_lists','user_updated','mailing_lists_user_updated_foreign','SET NULL'),
    ('meeting_requests','user_created','meeting_requests_user_created_foreign','SET NULL'),
    ('meeting_requests','user_updated','meeting_requests_user_updated_foreign','SET NULL'),
    ('menus','user_created','menus_user_created_foreign','SET NULL'),
    ('menus','user_updated','menus_user_updated_foreign','SET NULL'),
    ('messages','user_created','messages_user_created_foreign','SET NULL'),
    ('messages','user_updated','messages_user_updated_foreign','SET NULL'),
    ('newsletter_blocks','user_created','newsletter_blocks_user_created_foreign','SET NULL'),
    ('newsletter_blocks','user_updated','newsletter_blocks_user_updated_foreign','SET NULL'),
    ('options','user_created','options_user_created_foreign','SET NULL'),
    ('options','user_updated','options_user_updated_foreign','SET NULL'),
    ('organizations','user_created','organizations_user_created_foreign','SET NULL'),
    ('organizations','user_updated','organizations_user_updated_foreign','SET NULL'),
    ('page_agency','user_created','page_agency_user_created_foreign','SET NULL'),
    ('page_agency','user_updated','page_agency_user_updated_foreign','SET NULL'),
    ('page_home','user_created','page_home_user_created_foreign','SET NULL'),
    ('page_home','user_updated','page_home_user_updated_foreign','SET NULL'),
    ('page_industries','user_created','page_industries_user_created_foreign','SET NULL'),
    ('page_industries','user_updated','page_industries_user_updated_foreign','SET NULL'),
    ('page_portfolio','user_created','page_portfolio_user_created_foreign','SET NULL'),
    ('page_portfolio','user_updated','page_portfolio_user_updated_foreign','SET NULL'),
    ('page_services','user_created','page_services_user_created_foreign','SET NULL'),
    ('page_services','user_updated','page_services_user_updated_foreign','SET NULL'),
    ('payments_received','user_created','payments_received_user_created_foreign','SET NULL'),
    ('payments_received','user_updated','payments_received_user_updated_foreign','SET NULL'),
    ('people','user_created','people_user_created_foreign','SET NULL'),
    ('people','user_updated','people_user_updated_foreign','SET NULL'),
    ('phone_settings','user_created','phone_settings_user_created_foreign','SET NULL'),
    ('phone_settings','user_updated','phone_settings_user_updated_foreign','SET NULL'),
    ('portfolio','user_created','portfolio_user_created_foreign','SET NULL'),
    ('portfolio','user_updated','portfolio_user_updated_foreign','SET NULL'),
    ('products','user_created','products_user_created_foreign','SET NULL'),
    ('products','user_updated','products_user_updated_foreign','SET NULL'),
    ('project_events','user_created','project_events_user_created_foreign','SET NULL'),
    ('project_events','user_updated','project_events_user_updated_foreign','SET NULL'),
    ('projects','user_created','projects_user_created_foreign','SET NULL'),
    ('projects','user_updated','projects_user_updated_foreign','SET NULL'),
    ('prompts','user_created','prompts_user_created_foreign','SET NULL'),
    ('prompts','user_updated','prompts_user_updated_foreign','SET NULL'),
    ('proposals','user_created','proposals_user_created_foreign','SET NULL'),
    ('proposals','user_updated','proposals_user_updated_foreign','SET NULL'),
    ('reactions','user_created','reactions_user_created_foreign','SET NULL'),
    ('reactions','user_updated','reactions_user_updated_foreign','SET NULL'),
    ('requests','user_created','requests_user_created_foreign','SET NULL'),
    ('requests','user_updated','requests_user_updated_foreign','SET NULL'),
    ('restaurants','user_created','restaurants_user_created_foreign','SET NULL'),
    ('restaurants','user_updated','restaurants_user_updated_foreign','SET NULL'),
    ('reveal_blocks','user_created','reveal_blocks_user_created_foreign','SET NULL'),
    ('reveal_blocks','user_updated','reveal_blocks_user_updated_foreign','SET NULL'),
    ('scheduler_settings','user_created','scheduler_settings_user_created_foreign','SET NULL'),
    ('services','user_created','services_user_created_foreign','SET NULL'),
    ('services','user_updated','services_user_updated_foreign','SET NULL'),
    ('shop_categories','user_created','shop_categories_user_created_foreign','SET NULL'),
    ('shop_categories','user_updated','shop_categories_user_updated_foreign','SET NULL'),
    ('shop_order_items','user_created','shop_order_items_user_created_foreign','SET NULL'),
    ('shop_order_items','user_updated','shop_order_items_user_updated_foreign','SET NULL'),
    ('shop_orders','user_created','shop_orders_user_created_foreign','SET NULL'),
    ('shop_orders','user_updated','shop_orders_user_updated_foreign','SET NULL'),
    ('shop_products','user_created','shop_products_user_created_foreign','SET NULL'),
    ('shop_products','user_updated','shop_products_user_updated_foreign','SET NULL'),
    ('shop_settings','user_created','shop_settings_user_created_foreign','SET NULL'),
    ('shop_settings','user_updated','shop_settings_user_updated_foreign','SET NULL'),
    ('shop_shipping_options','user_created','shop_shipping_options_user_created_foreign','SET NULL'),
    ('shop_shipping_options','user_updated','shop_shipping_options_user_updated_foreign','SET NULL'),
    ('shop_variants','user_created','shop_variants_user_created_foreign','SET NULL'),
    ('shop_variants','user_updated','shop_variants_user_updated_foreign','SET NULL'),
    ('slides','user_created','slides_user_created_foreign','SET NULL'),
    ('slides','user_updated','slides_user_updated_foreign','SET NULL'),
    ('social_accounts','user_created','social_accounts_user_created_foreign','SET NULL'),
    ('social_accounts','user_updated','social_accounts_user_updated_foreign','SET NULL'),
    ('social_activity_log','user_created','social_activity_log_user_created_foreign','SET NULL'),
    ('social_activity_log','user_updated','social_activity_log_user_updated_foreign','SET NULL'),
    ('social_analytics_snapshots','user_created','social_analytics_snapshots_user_created_foreign','SET NULL'),
    ('social_analytics_snapshots','user_updated','social_analytics_snapshots_user_updated_foreign','SET NULL'),
    ('social_comments','user_created','social_comments_user_created_foreign','SET NULL'),
    ('social_comments','user_updated','social_comments_user_updated_foreign','SET NULL'),
    ('social_posts','approved_by','social_posts_approved_by_foreign','SET NULL'),
    ('social_posts','user_created','social_posts_user_created_foreign','SET NULL'),
    ('social_posts','user_updated','social_posts_user_updated_foreign','SET NULL'),
    ('tasks','user_created','tasks_user_created_foreign','SET NULL'),
    ('tasks','user_updated','tasks_user_updated_foreign','SET NULL'),
    ('teams','user_created','teams_user_created_foreign','SET NULL'),
    ('teams','user_updated','teams_user_updated_foreign','SET NULL'),
    ('tickets','user_created','tickets_user_created_foreign','SET NULL'),
    ('tickets','user_updated','tickets_user_updated_foreign','SET NULL'),
    ('user_presence','user_created','user_presence_user_created_foreign','SET NULL'),
    ('user_presence','user_updated','user_presence_user_updated_foreign','SET NULL'),
    ('video_meetings','user_created','video_meetings_user_created_foreign','SET NULL'),
    ('video_meetings','user_updated','video_meetings_user_updated_foreign','SET NULL'),
    ('videos','user_created','videos_user_created_foreign','SET NULL'),
    ('videos','user_updated','videos_user_updated_foreign','SET NULL')
  ) AS t(tbl, col, con, rule)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = r.tbl AND column_name = r.col
    ) THEN
      RAISE NOTICE 'skip %.% (no such column)', r.tbl, r.col;
      CONTINUE;
    END IF;

    IF r.rule = 'CASCADE' THEN
      EXECUTE format(
        'DELETE FROM %I WHERE %I IS NOT NULL AND NOT EXISTS (SELECT 1 FROM directus_users u WHERE u.id = %I.%I)',
        r.tbl, r.col, r.tbl, r.col);
    ELSE
      EXECUTE format(
        'UPDATE %I SET %I = NULL WHERE %I IS NOT NULL AND NOT EXISTS (SELECT 1 FROM directus_users u WHERE u.id = %I.%I)',
        r.tbl, r.col, r.col, r.tbl, r.col);
    END IF;
    GET DIAGNOSTICS n_clean = ROW_COUNT;
    IF n_clean > 0 THEN
      RAISE NOTICE 'cleaned % orphan(s) on %.%', n_clean, r.tbl, r.col;
    END IF;

    -- The Directus API mis-reports nullability for some columns (e.g.
    -- time_entries.user), so a SET NULL FK can land on a NOT NULL column and
    -- then fail at delete time. If we're about to SET NULL, widen the column.
    IF r.rule <> 'CASCADE' AND EXISTS (
      SELECT 1 FROM pg_attribute a
      JOIN pg_class cl ON cl.oid = a.attrelid
      JOIN pg_namespace ns ON ns.oid = cl.relnamespace AND ns.nspname = 'public'
      WHERE cl.relname = r.tbl AND a.attname = r.col AND a.attnum > 0 AND a.attnotnull
    ) THEN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP NOT NULL', r.tbl, r.col);
      RAISE NOTICE 'dropped NOT NULL on %.% so SET NULL can apply', r.tbl, r.col;
    END IF;

    EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', r.tbl, r.con);
    EXECUTE format(
      'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES directus_users(id) ON DELETE ' || r.rule,
      r.tbl, r.con, r.col);
  END LOOP;
END
$mig$;
