#!/usr/bin/env npx tsx
/**
 * Directus — Earnest Demo (Solo) org + user + seed data
 *
 * Provisions the solo-studio demo: one org, one Member-role user, a
 * believable slice of one-person-studio seed data. Anonymous visitors who
 * pick "Solo studio" on /try-demo land here.
 *
 * Idempotent: every create is guarded by a find-by-key check; re-running
 * the script never duplicates data.
 *
 * AI is capped via the existing org token budget (10K tokens/month + 3
 * scan credits/month). The Member role in this org has `ai_usage` bumped
 * to access+read+create so demo visitors can actually use Ask Earnest
 * (normal Member role has ai_usage disabled — the token budget is the
 * real cap).
 *
 * Usage:
 *   DEMO_USER_PASSWORD=<secret> pnpm tsx scripts/setup-demo-org.ts
 *
 * If DEMO_USER_PASSWORD is unset, the script generates one and prints it.
 * Save it to your env — /api/auth/demo-login reads the same variable.
 */

import 'dotenv/config';
import { DEFAULT_ROLE_PERMISSIONS } from '../shared/permissions';
import type { PermissionMatrix } from '../shared/permissions';
import {
	assertDirectusToken,
	directusRequest,
	ensureMembership,
	ensureRoles,
	ensureUser,
	findOrCreate,
	findOne,
	generatePassword,
	pingDirectus,
	randomToken,
} from './lib/demo-seed';

const DEMO_ORG_NAME = 'Earnest Demo — Solo';
const DEMO_ORG_SHORT = 'SOLO';
const DEMO_ORG_CODE = 'SOL'; // 3-letter code used as the invoice-code prefix.
const DEMO_ORG_SLUG = 'earnest-demo-solo'; // idempotency key after scripts/add-organizations-slug.ts runs.
const DEMO_USER_EMAIL = process.env.DEMO_USER_EMAIL || 'demo@earnest.guru';
const DEMO_USER_FIRST = 'Demo';
const DEMO_USER_LAST = 'Solo';
const DEMO_AI_TOKEN_LIMIT_MONTHLY = 10_000;
const DEMO_SCAN_LIMIT_MONTHLY = 3;

let demoPassword = process.env.DEMO_USER_PASSWORD || '';
let generatedPassword = false;
if (!demoPassword) {
	demoPassword = generatePassword();
	generatedPassword = true;
}

assertDirectusToken();

// Override Member.ai_usage for the demo org so visitors can chat with Earnest.
// Real-world cap is enforced by the org token budget, not the perm matrix.
const DEMO_MEMBER_PERMISSIONS: PermissionMatrix = {
	...DEFAULT_ROLE_PERMISSIONS.member,
	ai_usage: { access: true, read: true, create: true, update: false, delete: false },
};

async function ensureOrg(): Promise<any | null> {
	// Match by slug (stable URL-safe key). Fall back to legacy names so a
	// pre-slug org gets upgraded in place rather than duplicated.
	const existing =
		(await findOne<any>('organizations', { slug: { _eq: DEMO_ORG_SLUG } })) ||
		(await findOne<any>('organizations', { name: { _eq: DEMO_ORG_NAME } })) ||
		(await findOne<any>('organizations', { name: { _eq: 'Earnest Demo' } }));
	if (existing) {
		console.log(`  [skip] org "${DEMO_ORG_NAME}" (id=${existing.id})`);
		await directusRequest(`/items/organizations/${existing.id}`, 'PATCH', {
			name: DEMO_ORG_NAME,
			slug: DEMO_ORG_SLUG,
			short_name: DEMO_ORG_SHORT,
			code: DEMO_ORG_CODE,
			ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
			scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
		});
		return existing;
	}
	const res = await directusRequest<any>('/items/organizations', 'POST', {
		name: DEMO_ORG_NAME,
		slug: DEMO_ORG_SLUG,
		short_name: DEMO_ORG_SHORT,
		code: DEMO_ORG_CODE,
		status: 'published',
		active: true,
		plan: 'solo',
		ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
		ai_tokens_used_this_period: 0,
		scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
		scans_used_this_period: 0,
		notes: 'Public solo demo workspace. Seed regenerated by scripts/setup-demo-org.ts.',
	});
	if (!res.ok) {
		console.error(`  [fail] create org: ${res.error}`);
		return null;
	}
	console.log(`  [ok]   org "${DEMO_ORG_NAME}" (id=${res.data?.id})`);
	return res.data;
}

// ─── Seed data (solo-studio flavor) ──────────────────────────────────────

const CLIENT_SEEDS = [
	{ key: 'helios-studio', name: 'Helios Studio', industry: 'Hospitality', website: 'https://helios.example', account_state: 'active', code: 'HEL' },
	{ key: 'meridian-law', name: 'Meridian Law Group', industry: 'Legal', website: 'https://meridian.example', account_state: 'prospect', code: 'MER' },
];

async function seedClients(orgId: string): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CLIENT_SEEDS) {
		const row = await findOrCreate<any>(
			'clients',
			{ _and: [{ organization: { _eq: orgId } }, { slug: { _eq: c.key } }] },
			{
				name: c.name,
				slug: c.key,
				organization: orgId,
				industry: c.industry,
				website: c.website,
				account_state: c.account_state,
				code: c.code,
				status: 'published',
				notes: 'Solo demo seed.',
			},
			`client "${c.name}"`,
		);
		if (row) ids[c.key] = row.id;
	}
	return ids;
}

const CONTACT_SEEDS: Array<{
	first_name: string;
	last_name: string;
	email: string;
	title: string;
	company: string;
	category: 'client' | 'prospect' | 'partner' | 'architect' | 'developer' | 'hospitality' | 'media';
	clientKey?: string;
	notes?: string;
}> = [
	{ first_name: 'Sonia', last_name: 'Reyes', email: 'sonia@helios.example', title: 'Owner', company: 'Helios Studio', category: 'client', clientKey: 'helios-studio', notes: 'Primary contact at Helios.' },
	{ first_name: 'David', last_name: 'Park', email: 'david@helios.example', title: 'Head of Operations', company: 'Helios Studio', category: 'client', clientKey: 'helios-studio' },
	{ first_name: 'Amara', last_name: 'Okafor', email: 'amara@meridian.example', title: 'Managing Partner', company: 'Meridian Law Group', category: 'prospect', clientKey: 'meridian-law' },
	{ first_name: 'Julia', last_name: 'Holt', email: 'julia@atlas.example', title: 'VP Marketing', company: 'Atlas Fintech', category: 'prospect' },
	{ first_name: 'Rae', last_name: 'Nakamura', email: 'rae.nakamura@example.com', title: 'Co-Founder', company: 'Driftwood Roasters', category: 'prospect' },
	{ first_name: 'Elena', last_name: 'Vargas', email: 'elena@vargasrealty.example', title: 'Broker', company: 'Vargas Realty', category: 'partner', notes: 'Referral partner.' },
];

async function seedContacts(
	orgId: string,
	clientIds: Record<string, string>,
): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CONTACT_SEEDS) {
		const clientId = c.clientKey ? clientIds[c.clientKey] : null;
		const contact = await findOrCreate<any>(
			'contacts',
			{
				_and: [
					{ email: { _eq: c.email } },
					{ organizations: { organizations_id: { _eq: orgId } } },
				],
			},
			{
				first_name: c.first_name,
				last_name: c.last_name,
				email: c.email,
				title: c.title,
				company: c.company,
				category: c.category,
				client: clientId,
				source: 'demo',
				status: 'published',
				notes: c.notes || null,
				email_subscribed: true,
				unsubscribe_token: randomToken(),
			},
			`contact ${c.first_name} ${c.last_name}`,
		);
		if (contact) {
			ids[c.email] = contact.id;
			await findOrCreate(
				'contacts_organizations',
				{ _and: [{ contacts_id: { _eq: contact.id } }, { organizations_id: { _eq: orgId } }] },
				{ contacts_id: contact.id, organizations_id: orgId },
				`contact junction (${c.first_name})`,
			);
		}
	}
	return ids;
}

async function seedLeads(
	orgId: string,
	contactIds: Record<string, string>,
	clientIds: Record<string, string>,
): Promise<number[]> {
	const leads = [
		{
			contactEmail: 'julia@atlas.example',
			stage: 'contacted',
			priority: 'medium',
			source: 'website',
			source_details: 'Site form.',
			estimated_value: 42_000,
			project_type: 'Marketing site redesign',
			timeline: '3-6 months',
			tags: ['rfp'],
			notes: 'First intro call scheduled for next week.',
		},
		{
			contactEmail: 'rae.nakamura@example.com',
			stage: 'won',
			priority: 'medium',
			source: 'referral',
			source_details: 'Existing client referred them.',
			estimated_value: 28_000,
			actual_value: 31_500,
			project_type: 'Rebrand + packaging',
			timeline: 'flexible',
			closed_date: new Date().toISOString().slice(0, 10),
			resulting_client_key: 'helios-studio',
			tags: ['hot'],
			notes: 'Contracts signed.',
		},
	];
	const created: number[] = [];
	for (const l of leads) {
		const relatedContact = contactIds[l.contactEmail];
		const resultingClient = (l as any).resulting_client_key ? clientIds[(l as any).resulting_client_key] : null;
		if (!relatedContact) continue;
		const row = await findOrCreate<any>(
			'leads',
			{
				_and: [
					{ organization: { _eq: orgId } },
					{ related_contact: { _eq: relatedContact } },
					{ project_type: { _eq: l.project_type } },
				],
			},
			{
				organization: orgId,
				related_contact: relatedContact,
				stage: l.stage,
				priority: l.priority,
				source: l.source,
				source_details: l.source_details,
				estimated_value: l.estimated_value,
				actual_value: (l as any).actual_value ?? null,
				project_type: l.project_type,
				timeline: l.timeline,
				tags: l.tags,
				notes: l.notes,
				closed_date: (l as any).closed_date ?? null,
				resulting_client: resultingClient,
				status: 'published',
			},
			`lead (${l.contactEmail} / ${l.stage})`,
		);
		if (row) created.push(row.id);
	}
	return created;
}

async function seedProject(
	orgId: string,
	clientIds: Record<string, string>,
): Promise<string | null> {
	const row = await findOrCreate<any>(
		'projects',
		{ _and: [{ organization: { _eq: orgId } }, { title: { _eq: 'Helios West Hotel Launch' } }] },
		{
			title: 'Helios West Hotel Launch',
			description: 'Brand rollout + launch campaign.',
			organization: orgId,
			client: clientIds['helios-studio'],
			status: 'In Progress',
			contract_value: 140_000,
			template: 'branding-project',
			start_date: new Date().toISOString().slice(0, 10),
		},
		`project "Helios West Hotel Launch"`,
	);
	return row?.id ?? null;
}

async function seedProduct(): Promise<string | null> {
	const row = await findOrCreate<any>(
		'products',
		{ name: { _eq: 'Demo Services' } },
		{ name: 'Demo Services', status: 'published', description: 'Generic line item for demo invoices.' },
		`product "Demo Services"`,
	);
	return row?.id ?? null;
}

async function seedInvoice(
	orgId: string,
	clientIds: Record<string, string>,
	productId: string | null,
): Promise<void> {
	const today = new Date();
	const addDays = (d: Date, days: number) => {
		const nd = new Date(d);
		nd.setDate(nd.getDate() + days);
		return nd;
	};
	const iso = (d: Date) => d.toISOString().slice(0, 10);

	const client = clientIds['helios-studio'];
	if (!client) return;

	// Format matches app/composables/useInvoices.ts::generateInvoiceCode:
	//   INV-{ORG_CODE}-{CLIENT_CODE}-{YEAR}-{NNNN}
	const year = today.getFullYear();
	const invoiceCode = `INV-${DEMO_ORG_CODE}-HEL-${year}-0042`;

	const row = await findOrCreate<any>(
		'invoices',
		{ _and: [{ bill_to: { _eq: orgId } }, { invoice_code: { _eq: invoiceCode } }] },
		{
			bill_to: orgId,
			client,
			invoice_code: invoiceCode,
			status: 'paid',
			invoice_date: iso(addDays(today, -30)),
			due_date: iso(addDays(today, -15)),
			total_amount: 18_500,
			note: 'Helios West Hotel — brand system phase 1.',
		},
		`invoice ${invoiceCode}`,
	);
	if (row && productId) {
		await findOrCreate(
			'line_items',
			{ _and: [{ invoice_id: { _eq: row.id } }, { description: { _eq: 'Brand system — phase 1' } }] },
			{
				invoice_id: row.id,
				product: productId,
				description: 'Brand system — phase 1',
				rate: 18_500,
				quantity: 1,
				amount: 18_500,
			},
			`line_item ${invoiceCode}`,
		);
	}
}

async function seedQuickTasks(
	orgId: string,
	projectId: string | null,
	clientIds: Record<string, string>,
): Promise<void> {
	const tasks: Array<{
		title: string;
		schedule: 'today' | 'this_week' | 'later';
		priority: 'low' | 'medium' | 'high' | 'urgent';
		status: 'new' | 'in_progress' | 'completed';
		category: 'quick' | 'ticket' | 'project';
		clientKey?: string;
	}> = [
		{ title: 'Reply to Julia Holt re: intro call', schedule: 'today', priority: 'high', status: 'new', category: 'quick' },
		{ title: 'Draft launch carousel copy', schedule: 'this_week', priority: 'medium', status: 'in_progress', category: 'project', clientKey: 'helios-studio' },
		{ title: 'Confirm HEL-0042 payment received', schedule: 'today', priority: 'medium', status: 'completed', category: 'project', clientKey: 'helios-studio' },
	];
	for (const t of tasks) {
		await findOrCreate(
			'tasks',
			{ _and: [{ organization_id: { _eq: orgId } }, { title: { _eq: t.title } }] },
			{
				title: t.title,
				organization_id: orgId,
				project_id: projectId,
				client_id: t.clientKey ? clientIds[t.clientKey] || null : null,
				schedule: t.schedule,
				priority: t.priority,
				status: t.status,
				category: t.category,
			},
			`task "${t.title}"`,
		);
	}
}

// ─── Main ─────────────────────────────────────────────────────────────────

async function main() {
	console.log('=========================================');
	console.log('  Earnest Demo (Solo) — org + user + seed');
	console.log('=========================================');
	console.log(`Target: ${process.env.DIRECTUS_URL || 'http://localhost:8055'}\n`);

	await pingDirectus();

	console.log('--- org ---');
	const org = await ensureOrg();
	if (!org) process.exit(1);

	console.log('\n--- system roles ---');
	const roles = await ensureRoles(org.id, { member: DEMO_MEMBER_PERMISSIONS });
	if (!roles.member) {
		console.error('No Member role id — aborting.');
		process.exit(1);
	}

	console.log('\n--- demo user ---');
	const user = await ensureUser({
		email: DEMO_USER_EMAIL,
		password: demoPassword,
		firstName: DEMO_USER_FIRST,
		lastName: DEMO_USER_LAST,
	});
	if (!user) process.exit(1);

	console.log('\n--- membership ---');
	await ensureMembership(org.id, user.id, roles.member, 'solo demo → Member');

	console.log('\n--- clients ---');
	const clientIds = await seedClients(org.id);

	console.log('\n--- contacts ---');
	const contactIds = await seedContacts(org.id, clientIds);

	console.log('\n--- leads ---');
	await seedLeads(org.id, contactIds, clientIds);

	console.log('\n--- project ---');
	const projectId = await seedProject(org.id, clientIds);

	console.log('\n--- product + invoice ---');
	const productId = await seedProduct();
	await seedInvoice(org.id, clientIds, productId);

	console.log('\n--- quick tasks ---');
	await seedQuickTasks(org.id, projectId, clientIds);

	console.log('\n=========================================');
	console.log('  Summary');
	console.log('=========================================');
	console.log(`  Org ID:  ${org.id}`);
	console.log(`  User ID: ${user.id}`);
	console.log(`  Email:   ${DEMO_USER_EMAIL}`);
	if (generatedPassword) {
		console.log('');
		console.log('  ⚠ Generated a new demo password. Save this to your env as');
		console.log('    DEMO_USER_PASSWORD — /api/auth/demo-login reads it on every request.');
		console.log(`    DEMO_USER_PASSWORD="${demoPassword}"`);
	} else {
		console.log('  Password: (from env DEMO_USER_PASSWORD)');
	}
	console.log('\nDone.');
}

main().catch((err) => {
	console.error('Setup failed:', err);
	process.exit(1);
});
