#!/usr/bin/env npx tsx
/**
 * Directus — Earnest Demo (Agency) org + users + seed data
 *
 * Provisions the multi-seat agency demo: one org with an Admin-role
 * primary demo user + several Member-role teammates, plus a richer seed
 * that exercises the Admin-only surfaces (Team Management, Marketing,
 * Member Management) hidden from the solo demo.
 *
 * Idempotent: every create is guarded by a find-by-key check.
 *
 * The Admin role in this demo org has destructive org-level actions
 * (org_settings.delete) scrubbed so a visitor can't nuke the shared
 * workspace. requireOrgRole() still bars direct hits to Stripe/cleanup
 * endpoints — this is belt + suspenders.
 *
 * Usage:
 *   DEMO_AGENCY_USER_PASSWORD=<secret> pnpm tsx scripts/setup-demo-agency-org.ts
 *
 * If DEMO_AGENCY_USER_PASSWORD is unset, the script generates one and
 * prints it. Save it to your env — /api/auth/demo-agency-login reads the
 * same variable.
 */

import 'dotenv/config';
import { DEFAULT_ROLE_PERMISSIONS } from '../shared/permissions';
import type { PermissionMatrix } from '../shared/permissions';
import {
	assertDirectusToken,
	directusRequest,
	ensureMembership,
	ensureRoles,
	ensureUser,
	findOrCreate,
	findOne,
	generatePassword,
	pingDirectus,
	randomToken,
} from './lib/demo-seed';

const DEMO_ORG_NAME = 'Earnest Demo — Agency';
const DEMO_ORG_SHORT = 'AGENCY';
const DEMO_ORG_CODE = 'AGY'; // Used as the prefix on invoice codes.
const DEMO_ORG_SLUG = 'earnest-demo-agency'; // idempotency key after scripts/add-organizations-slug.ts runs.
const DEMO_ADMIN_EMAIL = process.env.DEMO_AGENCY_USER_EMAIL || 'demo-agency@earnest.guru';
const DEMO_ADMIN_FIRST = 'Demo';
const DEMO_ADMIN_LAST = 'Agency';
const DEMO_AI_TOKEN_LIMIT_MONTHLY = 10_000;
const DEMO_SCAN_LIMIT_MONTHLY = 3;

let demoPassword = process.env.DEMO_AGENCY_USER_PASSWORD || '';
let generatedPassword = false;
if (!demoPassword) {
	demoPassword = generatePassword();
	generatedPassword = true;
}

assertDirectusToken();

// Demo-Admin override: keep full CRUD on everything *except* org deletion
// (covered by requireOrgRole on destructive endpoints, but scrub here so
// the UI doesn't surface a delete-org action that then 403s). Also bump
// ai_usage so visitors can chat with Earnest — the 10K token budget is
// the real spend cap.
const DEMO_ADMIN_PERMISSIONS: PermissionMatrix = {
	...DEFAULT_ROLE_PERMISSIONS.admin,
	org_settings: { access: true, read: true, update: true, create: false, delete: false },
};

// Teammate Members also get ai_usage (normal Member has it disabled).
const DEMO_MEMBER_PERMISSIONS: PermissionMatrix = {
	...DEFAULT_ROLE_PERMISSIONS.member,
	ai_usage: { access: true, read: true, create: true, update: false, delete: false },
};

async function ensureOrg(): Promise<any | null> {
	// Match by slug (stable URL-safe key). Fall back to name so a pre-slug
	// org gets upgraded in place rather than duplicated.
	const existing =
		(await findOne<any>('organizations', { slug: { _eq: DEMO_ORG_SLUG } })) ||
		(await findOne<any>('organizations', { name: { _eq: DEMO_ORG_NAME } }));
	if (existing) {
		console.log(`  [skip] org "${DEMO_ORG_NAME}" (id=${existing.id})`);
		await directusRequest(`/items/organizations/${existing.id}`, 'PATCH', {
			slug: DEMO_ORG_SLUG,
			short_name: DEMO_ORG_SHORT,
			code: DEMO_ORG_CODE,
			ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
			scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
		});
		return existing;
	}
	const res = await directusRequest<any>('/items/organizations', 'POST', {
		name: DEMO_ORG_NAME,
		slug: DEMO_ORG_SLUG,
		short_name: DEMO_ORG_SHORT,
		code: DEMO_ORG_CODE,
		status: 'published',
		active: true,
		plan: 'agency',
		ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
		ai_tokens_used_this_period: 0,
		scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
		scans_used_this_period: 0,
		notes: 'Public agency demo workspace. Seed regenerated by scripts/setup-demo-agency-org.ts.',
	});
	if (!res.ok) {
		console.error(`  [fail] create org: ${res.error}`);
		return null;
	}
	console.log(`  [ok]   org "${DEMO_ORG_NAME}" (id=${res.data?.id})`);
	return res.data;
}

// ─── Seed data ────────────────────────────────────────────────────────────

const CLIENT_SEEDS: Array<{
	key: string;
	name: string;
	industry: string;
	website: string;
	account_state: 'active' | 'prospect' | 'inactive' | 'churned';
	code: string;
}> = [
	{ key: 'helios-studio', name: 'Helios Hospitality Group', industry: 'Hospitality', website: 'https://helios.example', account_state: 'active', code: 'HEL' },
	{ key: 'meridian-law', name: 'Meridian Law Group', industry: 'Legal', website: 'https://meridian.example', account_state: 'active', code: 'MER' },
	{ key: 'northwind-dev', name: 'Northwind Development', industry: 'Real Estate', website: 'https://northwind.example', account_state: 'prospect', code: 'NWD' },
	{ key: 'pinecrest-clinic', name: 'Pinecrest Clinic', industry: 'Healthcare', website: 'https://pinecrest.example', account_state: 'active', code: 'PIN' },
	{ key: 'atlas-fintech', name: 'Atlas Fintech', industry: 'Finance', website: 'https://atlas.example', account_state: 'inactive', code: 'ATL' },
	{ key: 'beacon-school', name: 'Beacon School', industry: 'Education', website: 'https://beacon.example', account_state: 'churned', code: 'BCN' },
];

async function seedClients(orgId: string): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CLIENT_SEEDS) {
		const row = await findOrCreate<any>(
			'clients',
			{ _and: [{ organization: { _eq: orgId } }, { slug: { _eq: c.key } }] },
			{
				name: c.name,
				slug: c.key,
				organization: orgId,
				industry: c.industry,
				website: c.website,
				account_state: c.account_state,
				code: c.code,
				status: 'published',
				notes: 'Agency demo seed.',
			},
			`client "${c.name}"`,
		);
		if (row) ids[c.key] = row.id;
	}
	return ids;
}

const CONTACT_SEEDS: Array<{
	first_name: string;
	last_name: string;
	email: string;
	title: string;
	company: string;
	category: 'client' | 'prospect' | 'partner' | 'architect' | 'developer' | 'hospitality' | 'media';
	clientKey?: string;
	notes?: string;
}> = [
	// Helios (active)
	{ first_name: 'Sonia', last_name: 'Reyes', email: 'sonia@helios.example', title: 'CEO', company: 'Helios Hospitality Group', category: 'client', clientKey: 'helios-studio', notes: 'Primary contact.' },
	{ first_name: 'David', last_name: 'Park', email: 'david@helios.example', title: 'Head of Ops', company: 'Helios Hospitality Group', category: 'client', clientKey: 'helios-studio' },
	{ first_name: 'Maya', last_name: 'Iyer', email: 'maya@helios.example', title: 'Marketing Lead', company: 'Helios Hospitality Group', category: 'client', clientKey: 'helios-studio' },
	// Meridian (active)
	{ first_name: 'Amara', last_name: 'Okafor', email: 'amara@meridian.example', title: 'Managing Partner', company: 'Meridian Law Group', category: 'client', clientKey: 'meridian-law' },
	{ first_name: 'Tom', last_name: 'Bennett', email: 'tom@meridian.example', title: 'Office Manager', company: 'Meridian Law Group', category: 'client', clientKey: 'meridian-law' },
	// Pinecrest (active)
	{ first_name: 'Priya', last_name: 'Shah', email: 'priya@pinecrest.example', title: 'Director of Patient Services', company: 'Pinecrest Clinic', category: 'client', clientKey: 'pinecrest-clinic' },
	{ first_name: 'Glen', last_name: 'Weaver', email: 'glen@pinecrest.example', title: 'CFO', company: 'Pinecrest Clinic', category: 'client', clientKey: 'pinecrest-clinic' },
	// Northwind (prospect)
	{ first_name: 'Marcus', last_name: 'Levi', email: 'marcus@northwind.example', title: 'Principal', company: 'Northwind Development', category: 'prospect', clientKey: 'northwind-dev' },
	{ first_name: 'Sana', last_name: 'Mirza', email: 'sana@northwind.example', title: 'Co-Principal', company: 'Northwind Development', category: 'prospect', clientKey: 'northwind-dev' },
	// Atlas (inactive)
	{ first_name: 'Julia', last_name: 'Holt', email: 'julia@atlas.example', title: 'VP Marketing', company: 'Atlas Fintech', category: 'client', clientKey: 'atlas-fintech' },
	// Beacon (churned)
	{ first_name: 'Pat', last_name: 'Dowling', email: 'pat@beacon.example', title: 'Head of School', company: 'Beacon School', category: 'client', clientKey: 'beacon-school' },

	// Free-floating prospects (no client yet)
	{ first_name: 'Rae', last_name: 'Nakamura', email: 'rae@driftwood.example', title: 'Co-Founder', company: 'Driftwood Roasters', category: 'prospect' },
	{ first_name: 'Owen', last_name: 'Frey', email: 'owen@frey-gallery.example', title: 'Director', company: 'Frey Gallery', category: 'prospect' },
	{ first_name: 'Dana', last_name: 'Ellis', email: 'dana@ellis-farms.example', title: 'Founder', company: 'Ellis Farms', category: 'prospect' },

	// Partners & vendors
	{ first_name: 'Elena', last_name: 'Vargas', email: 'elena@vargasrealty.example', title: 'Broker', company: 'Vargas Realty', category: 'partner', notes: 'Sourced Northwind.' },
	{ first_name: 'Hugo', last_name: 'Beck', email: 'hugo@beckcpa.example', title: 'Partner', company: 'Beck & Co CPA', category: 'partner', notes: 'Accounting referral partner.' },
	{ first_name: 'Naomi', last_name: 'Flores', email: 'naomi@flores-arch.example', title: 'Principal Architect', company: 'Flores Architecture', category: 'partner' },
	{ first_name: 'Liv', last_name: 'Carlson', email: 'liv@liv-pr.example', title: 'PR Director', company: 'Liv PR', category: 'partner' },

	// Media
	{ first_name: 'Kai', last_name: 'Ito', email: 'kai@designweekly.example', title: 'Editor', company: 'Design Weekly', category: 'media' },
	{ first_name: 'Ben', last_name: 'Wu', email: 'ben@wudesign.example', title: 'Senior Architect', company: 'Wu Design Partners', category: 'architect' },
	{ first_name: 'Farrah', last_name: 'Dolan', email: 'farrah@dolanbuilds.example', title: 'Project Manager', company: 'Dolan Construction', category: 'developer' },
];

async function seedContacts(
	orgId: string,
	clientIds: Record<string, string>,
): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CONTACT_SEEDS) {
		const clientId = c.clientKey ? clientIds[c.clientKey] : null;
		const contact = await findOrCreate<any>(
			'contacts',
			{
				_and: [
					{ email: { _eq: c.email } },
					{ organizations: { organizations_id: { _eq: orgId } } },
				],
			},
			{
				first_name: c.first_name,
				last_name: c.last_name,
				email: c.email,
				title: c.title,
				company: c.company,
				category: c.category,
				client: clientId,
				source: 'demo',
				status: 'published',
				notes: c.notes || null,
				email_subscribed: true,
				unsubscribe_token: randomToken(),
			},
			`contact ${c.first_name} ${c.last_name}`,
		);
		if (contact) {
			ids[c.email] = contact.id;
			await findOrCreate(
				'contacts_organizations',
				{ _and: [{ contacts_id: { _eq: contact.id } }, { organizations_id: { _eq: orgId } }] },
				{ contacts_id: contact.id, organizations_id: orgId },
				`contact junction (${c.first_name})`,
			);
		}
	}
	return ids;
}

async function seedContactConnections(
	clientIds: Record<string, string>,
	contactIds: Record<string, string>,
): Promise<void> {
	const connections = [
		{ contactEmail: 'elena@vargasrealty.example', clientKey: 'northwind-dev', role: 'referral_partner', introduced_by: 'partner', notes: 'Introduced Marcus at a ULI event.' },
		{ contactEmail: 'hugo@beckcpa.example', clientKey: 'helios-studio', role: 'consultant', introduced_by: 'us', notes: 'Handles quarterly books.' },
		{ contactEmail: 'naomi@flores-arch.example', clientKey: 'helios-studio', role: 'vendor', introduced_by: 'partner', notes: 'AOR on the West Hotel renovation.' },
		{ contactEmail: 'liv@liv-pr.example', clientKey: 'meridian-law', role: 'vendor', introduced_by: 'us', notes: 'Outside PR firm.' },
		{ contactEmail: 'kai@designweekly.example', clientKey: 'helios-studio', role: 'media', introduced_by: 'us', notes: 'Covered the Helios opening.' },
	];
	for (const c of connections) {
		const contact = contactIds[c.contactEmail];
		const client = clientIds[c.clientKey];
		if (!contact || !client) continue;
		await findOrCreate(
			'contact_connections',
			{ _and: [{ contact: { _eq: contact } }, { client: { _eq: client } }, { role: { _eq: c.role } }] },
			{ contact, client, role: c.role, introduced_by: c.introduced_by, notes: c.notes },
			`contact_connection ${c.contactEmail} → ${c.clientKey}`,
		);
	}
}

async function seedLeads(
	orgId: string,
	contactIds: Record<string, string>,
	clientIds: Record<string, string>,
	adminUserId: string,
): Promise<number[]> {
	const leads = [
		{
			contactEmail: 'dana@ellis-farms.example',
			stage: 'new',
			priority: 'medium',
			source: 'website',
			project_type: 'Brand refresh + e-commerce',
			estimated_value: 54_000,
			timeline: '3-6 months',
			tags: ['website'],
			notes: 'Inbound site form — discovery call not yet scheduled.',
		},
		{
			contactEmail: 'owen@frey-gallery.example',
			stage: 'contacted',
			priority: 'medium',
			source: 'referral',
			project_type: 'Exhibition microsite + email',
			estimated_value: 22_000,
			timeline: '1-3 months',
			tags: ['referral'],
			notes: 'First call booked for next Tuesday.',
		},
		{
			contactEmail: 'marcus@northwind.example',
			stage: 'qualified',
			priority: 'high',
			source: 'referral',
			source_details: 'Introduced by Elena Vargas.',
			project_type: 'Brand + marketing site for mixed-use property',
			estimated_value: 85_000,
			timeline: '1-3 months',
			tags: ['hot', 'referral'],
			notes: 'Budget confirmed.',
		},
		{
			contactEmail: 'sana@northwind.example',
			stage: 'proposal_sent',
			priority: 'high',
			source: 'referral',
			project_type: 'Phase 2 — leasing campaign creative',
			estimated_value: 38_000,
			timeline: '3-6 months',
			tags: ['hot'],
			notes: 'SOW out for sig — 21-day validity.',
		},
		{
			contactEmail: 'rae@driftwood.example',
			stage: 'won',
			priority: 'medium',
			source: 'referral',
			project_type: 'Rebrand + packaging',
			estimated_value: 28_000,
			actual_value: 31_500,
			timeline: 'flexible',
			closed_date: new Date().toISOString().slice(0, 10),
			resulting_client_key: 'helios-studio',
			tags: ['hot'],
			notes: 'Kickoff next month.',
		},
	];
	const created: number[] = [];
	for (const l of leads) {
		const relatedContact = contactIds[l.contactEmail];
		const resultingClient = (l as any).resulting_client_key ? clientIds[(l as any).resulting_client_key] : null;
		if (!relatedContact) continue;
		const row = await findOrCreate<any>(
			'leads',
			{
				_and: [
					{ organization: { _eq: orgId } },
					{ related_contact: { _eq: relatedContact } },
					{ project_type: { _eq: l.project_type } },
				],
			},
			{
				organization: orgId,
				related_contact: relatedContact,
				stage: l.stage,
				priority: l.priority,
				source: l.source,
				source_details: (l as any).source_details ?? null,
				estimated_value: l.estimated_value,
				actual_value: (l as any).actual_value ?? null,
				project_type: l.project_type,
				timeline: l.timeline,
				tags: l.tags,
				notes: l.notes,
				closed_date: (l as any).closed_date ?? null,
				resulting_client: resultingClient,
				assigned_to: adminUserId,
				status: 'published',
			},
			`lead (${l.contactEmail} / ${l.stage})`,
		);
		if (row) created.push(row.id);
	}
	return created;
}

async function seedProjects(
	orgId: string,
	clientIds: Record<string, string>,
): Promise<Record<string, string>> {
	const out: Record<string, string> = {};
	const projects = [
		{
			key: 'helios-west-hotel',
			title: 'Helios West Hotel Launch',
			description: 'Full brand rollout + launch campaign for the West Village property.',
			clientKey: 'helios-studio',
			status: 'In Progress',
			contract_value: 140_000,
			template: 'branding-project',
		},
		{
			key: 'meridian-site-refresh',
			title: 'Meridian Site Refresh',
			description: 'Marketing site redesign with updated practice-area templates.',
			clientKey: 'meridian-law',
			status: 'In Progress',
			contract_value: 48_000,
			template: 'web-project',
		},
		{
			key: 'pinecrest-patient-portal',
			title: 'Pinecrest Patient Portal',
			description: 'Patient intake flow + booking portal.',
			clientKey: 'pinecrest-clinic',
			status: 'Scheduled',
			contract_value: 78_000,
			template: 'web-project',
		},
	];
	for (const p of projects) {
		const clientId = clientIds[p.clientKey];
		const row = await findOrCreate<any>(
			'projects',
			{ _and: [{ organization: { _eq: orgId } }, { title: { _eq: p.title } }] },
			{
				title: p.title,
				description: p.description,
				organization: orgId,
				client: clientId,
				status: p.status,
				contract_value: p.contract_value,
				template: p.template,
				start_date: new Date().toISOString().slice(0, 10),
			},
			`project "${p.title}"`,
		);
		if (row) out[p.key] = row.id;
	}
	return out;
}

async function seedProjectEvents(
	projectIds: Record<string, string>,
): Promise<Record<string, string>> {
	const out: Record<string, string> = {};
	const today = new Date();
	const iso = (offsetDays: number) => {
		const d = new Date(today);
		d.setDate(d.getDate() + offsetDays);
		return d.toISOString().slice(0, 10);
	};

	const events: Array<{
		key: string;
		projectKey: string;
		title: string;
		description: string;
		type: 'General' | 'Design' | 'Content' | 'Timeline' | 'Financial' | 'Hours';
		status: 'draft' | 'Scheduled' | 'Active' | 'Completed' | 'archived';
		approval?: 'No Approval Necessary' | 'Need Approval' | 'Approved';
		is_milestone?: boolean;
		event_date: string;
		duration_days?: number;
	}> = [
		// Helios — 4 events
		{ key: 'helios-discovery', projectKey: 'helios-west-hotel', title: 'Discovery + stakeholder interviews', description: 'GM, chef, ops lead interviews.', type: 'General', status: 'Completed', event_date: iso(-28), duration_days: 5 },
		{ key: 'helios-brand-v1', projectKey: 'helios-west-hotel', title: 'Brand system — v1 concepts', description: 'Three concept directions.', type: 'Design', status: 'Completed', approval: 'Approved', event_date: iso(-14), duration_days: 10 },
		{ key: 'helios-site-build', projectKey: 'helios-west-hotel', title: 'Launch site build', description: 'Marketing site + reservation handoff.', type: 'Design', status: 'Active', approval: 'Need Approval', event_date: iso(5), duration_days: 14 },
		{ key: 'helios-opening', projectKey: 'helios-west-hotel', title: 'Opening ceremony', description: 'Public launch + press walkthrough.', type: 'Timeline', status: 'Scheduled', is_milestone: true, event_date: iso(21) },

		// Meridian — 3 events
		{ key: 'meridian-kickoff', projectKey: 'meridian-site-refresh', title: 'Kickoff + content inventory', description: 'Walk the current sitemap.', type: 'General', status: 'Completed', event_date: iso(-12), duration_days: 3 },
		{ key: 'meridian-wireframes', projectKey: 'meridian-site-refresh', title: 'Practice-page wireframes', description: 'Two layout options.', type: 'Design', status: 'Active', approval: 'Need Approval', event_date: iso(2), duration_days: 5 },
		{ key: 'meridian-launch', projectKey: 'meridian-site-refresh', title: 'Site launch', description: 'Cutover + redirects.', type: 'Timeline', status: 'Scheduled', is_milestone: true, event_date: iso(35) },

		// Pinecrest — 3 events
		{ key: 'pinecrest-kickoff', projectKey: 'pinecrest-patient-portal', title: 'Discovery — patient flow mapping', description: 'Shadow check-in, intake, booking.', type: 'General', status: 'Scheduled', event_date: iso(10), duration_days: 4 },
		{ key: 'pinecrest-wireframes', projectKey: 'pinecrest-patient-portal', title: 'Portal wireframes', description: 'Booking + intake flows.', type: 'Design', status: 'Scheduled', approval: 'Need Approval', event_date: iso(25), duration_days: 7 },
		{ key: 'pinecrest-launch', projectKey: 'pinecrest-patient-portal', title: 'Soft launch', description: 'Limited rollout to one clinic.', type: 'Timeline', status: 'Scheduled', is_milestone: true, event_date: iso(80) },
	];
	for (const e of events) {
		const projectId = projectIds[e.projectKey];
		if (!projectId) continue;
		const row = await findOrCreate<any>(
			'project_events',
			{ _and: [{ project: { _eq: projectId } }, { title: { _eq: e.title } }] },
			{
				project: projectId,
				title: e.title,
				description: e.description,
				type: e.type,
				status: e.status,
				approval: e.approval ?? 'No Approval Necessary',
				is_milestone: e.is_milestone ?? false,
				event_date: e.event_date,
				duration_days: e.duration_days ?? null,
			},
			`project_event "${e.title}"`,
		);
		if (row) out[e.key] = row.id;
	}
	return out;
}

async function seedProjectTasks(
	projectIds: Record<string, string>,
	eventIds: Record<string, string>,
	memberUserIds: string[],
): Promise<void> {
	const pick = (i: number) => memberUserIds[i % Math.max(memberUserIds.length, 1)] || null;
	const tasks: Array<{
		projectKey: string;
		eventKey: string;
		title: string;
		description: string;
		completed?: boolean;
		priority?: 'low' | 'medium' | 'high';
		assigneeIdx?: number;
	}> = [
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-discovery', title: 'GM interview notes', description: 'Capture quotes.', completed: true, priority: 'medium', assigneeIdx: 0 },
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-discovery', title: 'Ops walkthrough — BOH', description: 'Photo reference.', completed: true, priority: 'low', assigneeIdx: 1 },
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-brand-v1', title: 'Package concepts for review', description: 'PDF + Figma share link.', completed: true, priority: 'high', assigneeIdx: 0 },
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-site-build', title: 'Reservation schema handoff', description: 'Document required fields + UTM tagging.', priority: 'high', assigneeIdx: 2 },
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-site-build', title: 'Shoot hero gallery', description: 'Coordinate with Ben Wu.', priority: 'medium', assigneeIdx: 3 },
		{ projectKey: 'helios-west-hotel', eventKey: 'helios-site-build', title: 'Booking flow QA', description: 'Desktop + mobile pass.', priority: 'medium', assigneeIdx: 1 },

		{ projectKey: 'meridian-site-refresh', eventKey: 'meridian-kickoff', title: 'Pull analytics snapshot', description: '90-day top-20 pages.', completed: true, priority: 'medium', assigneeIdx: 2 },
		{ projectKey: 'meridian-site-refresh', eventKey: 'meridian-wireframes', title: 'Practice-area content model', description: 'Fields, repeaters, CTA slots.', priority: 'high', assigneeIdx: 0 },
		{ projectKey: 'meridian-site-refresh', eventKey: 'meridian-wireframes', title: 'Template review with Amara', description: 'Present both options.', priority: 'medium', assigneeIdx: 2 },
		{ projectKey: 'meridian-site-refresh', eventKey: 'meridian-launch', title: 'Redirect map', description: 'Map old URLs → new.', priority: 'high', assigneeIdx: 3 },

		{ projectKey: 'pinecrest-patient-portal', eventKey: 'pinecrest-kickoff', title: 'Patient intake audit', description: 'Current-state flowchart.', priority: 'high', assigneeIdx: 0 },
		{ projectKey: 'pinecrest-patient-portal', eventKey: 'pinecrest-kickoff', title: 'HIPAA requirements doc', description: 'Capture compliance constraints.', priority: 'high', assigneeIdx: 2 },
		{ projectKey: 'pinecrest-patient-portal', eventKey: 'pinecrest-wireframes', title: 'Booking flow wireframes', description: 'Desktop + mobile.', priority: 'high', assigneeIdx: 1 },
		{ projectKey: 'pinecrest-patient-portal', eventKey: 'pinecrest-wireframes', title: 'Intake form wireframes', description: 'Multi-step form with save state.', priority: 'medium', assigneeIdx: 0 },
		{ projectKey: 'pinecrest-patient-portal', eventKey: 'pinecrest-launch', title: 'Launch runbook', description: 'Rollout checklist + rollback plan.', priority: 'medium', assigneeIdx: 3 },
	];
	for (const t of tasks) {
		const projectId = projectIds[t.projectKey];
		const eventId = eventIds[t.eventKey];
		if (!projectId || !eventId) continue;
		await findOrCreate(
			'project_tasks',
			{ _and: [{ event_id: { _eq: eventId } }, { title: { _eq: t.title } }] },
			{
				event_id: eventId,
				project: projectId,
				title: t.title,
				description: t.description,
				completed: t.completed ?? false,
				completed_at: t.completed ? new Date().toISOString() : null,
				priority: t.priority || 'medium',
				assigned_to: typeof t.assigneeIdx === 'number' ? pick(t.assigneeIdx) : null,
				status: 'published',
			},
			`project_task "${t.title}"`,
		);
	}
}

async function seedProduct(): Promise<string | null> {
	const row = await findOrCreate<any>(
		'products',
		{ name: { _eq: 'Agency Services' } },
		{ name: 'Agency Services', status: 'published', description: 'Generic line item for agency demo invoices.' },
		`product "Agency Services"`,
	);
	return row?.id ?? null;
}

async function seedInvoices(
	orgId: string,
	clientIds: Record<string, string>,
	productId: string | null,
): Promise<void> {
	const today = new Date();
	const addDays = (d: Date, days: number) => {
		const nd = new Date(d);
		nd.setDate(nd.getDate() + days);
		return nd;
	};
	const iso = (d: Date) => d.toISOString().slice(0, 10);

	// Invoice status enum is pending | processing | paid | archived. We
	// represent "overdue" as a pending invoice whose due_date has passed —
	// the UI derives overdue from that.
	//
	// invoice_code is globally unique in Directus (not per-org). Format
	// matches `useInvoices.ts::generateInvoiceCode`:
	//   INV-{ORG_CODE}-{CLIENT_CODE}-{YEAR}-{NNNN}
	// orgCode=AGY keeps agency-demo codes distinct from the solo seed and
	// from any real customer data.
	const year = today.getFullYear();
	const fmt = (clientCode: string, n: number) =>
		`INV-${DEMO_ORG_CODE}-${clientCode}-${year}-${String(n).padStart(4, '0')}`;

	const invoices = [
		{
			code: fmt('HEL', 42),
			clientKey: 'helios-studio',
			status: 'paid',
			invoice_date: iso(addDays(today, -45)),
			due_date: iso(addDays(today, -30)),
			total_amount: 32_000,
			note: 'Helios West Hotel — brand phase 1.',
			line: { description: 'Brand system — phase 1', rate: 32_000, quantity: 1 },
		},
		{
			code: fmt('MER', 11),
			clientKey: 'meridian-law',
			status: 'pending',
			invoice_date: iso(addDays(today, -5)),
			due_date: iso(addDays(today, 25)),
			total_amount: 12_000,
			note: 'Meridian Site Refresh — discovery deposit.',
			line: { description: 'Discovery + sitemap workshop', rate: 12_000, quantity: 1 },
		},
		{
			code: fmt('ATL', 19),
			clientKey: 'atlas-fintech',
			status: 'pending',
			invoice_date: iso(addDays(today, -50)),
			due_date: iso(addDays(today, -20)),
			total_amount: 18_000,
			note: 'Atlas — paused retainer, prior period.',
			line: { description: 'Retainer — March', rate: 18_000, quantity: 1 },
		},
	];

	for (const inv of invoices) {
		const client = clientIds[inv.clientKey];
		if (!client) continue;
		const row = await findOrCreate<any>(
			'invoices',
			{ _and: [{ bill_to: { _eq: orgId } }, { invoice_code: { _eq: inv.code } }] },
			{
				bill_to: orgId,
				client,
				invoice_code: inv.code,
				status: inv.status,
				invoice_date: inv.invoice_date,
				due_date: inv.due_date,
				total_amount: inv.total_amount,
				note: inv.note,
			},
			`invoice ${inv.code}`,
		);
		if (row && productId) {
			await findOrCreate(
				'line_items',
				{ _and: [{ invoice_id: { _eq: row.id } }, { description: { _eq: inv.line.description } }] },
				{
					invoice_id: row.id,
					product: productId,
					description: inv.line.description,
					rate: inv.line.rate,
					quantity: inv.line.quantity,
					amount: inv.line.rate * inv.line.quantity,
				},
				`line_item ${inv.code}`,
			);
		}
	}
}

async function seedTickets(
	orgId: string,
	projectIds: Record<string, string>,
	clientIds: Record<string, string>,
	memberUserIds: string[],
): Promise<Record<string, string>> {
	const out: Record<string, string> = {};
	const tickets = [
		{
			key: 'helios-insta',
			title: 'Helios — Instagram launch assets',
			description: 'Carousel + story templates for launch week.',
			status: 'In Progress',
			priority: 'high',
			projectKey: 'helios-west-hotel',
			clientKey: 'helios-studio',
			assigneeIdx: 0,
		},
		{
			key: 'meridian-content-audit',
			title: 'Meridian — content audit of practice pages',
			description: 'Pull metrics per practice area and flag low-engagement content.',
			status: 'Pending',
			priority: 'medium',
			projectKey: 'meridian-site-refresh',
			clientKey: 'meridian-law',
			assigneeIdx: 2,
		},
		{
			key: 'pinecrest-compliance',
			title: 'Pinecrest — HIPAA compliance review',
			description: 'Intake portal field-level review against compliance checklist.',
			status: 'Scheduled',
			priority: 'high',
			projectKey: 'pinecrest-patient-portal',
			clientKey: 'pinecrest-clinic',
			assigneeIdx: 3,
		},
	];
	for (const t of tickets) {
		const assignee = memberUserIds[t.assigneeIdx] || null;
		const row = await findOrCreate<any>(
			'tickets',
			{ _and: [{ organization: { _eq: orgId } }, { title: { _eq: t.title } }] },
			{
				title: t.title,
				description: t.description,
				organization: orgId,
				project: projectIds[t.projectKey] || null,
				client: clientIds[t.clientKey] || null,
				status: t.status,
				priority: t.priority,
				due_date: new Date(Date.now() + 10 * 86_400_000).toISOString().slice(0, 10),
			},
			`ticket "${t.title}"`,
		);
		if (row) {
			out[t.key] = row.id;
			if (assignee) {
				await findOrCreate(
					'tickets_directus_users',
					{ _and: [{ tickets_id: { _eq: row.id } }, { directus_users_id: { _eq: assignee } }] },
					{ tickets_id: row.id, directus_users_id: assignee },
					`ticket assignment (${t.title})`,
				);
			}
		}
	}
	return out;
}

async function seedTeams(
	orgId: string,
	memberUserIds: string[],
): Promise<Record<string, string>> {
	const out: Record<string, string> = {};
	const teams = [
		{
			key: 'creative',
			name: 'Creative',
			description: 'Design + brand systems.',
			focus: 'Brand, identity, and visual systems.',
			goals: 'Ship 2 new brand systems per quarter.',
			memberIdxs: [0, 1],
			managerIdx: 0,
		},
		{
			key: 'delivery',
			name: 'Delivery',
			description: 'Project management + technical execution.',
			focus: 'PM, web build, launch ops.',
			goals: 'Maintain <5% schedule variance across active work.',
			memberIdxs: [2, 3],
			managerIdx: 2,
		},
	];
	for (const t of teams) {
		const team = await findOrCreate<any>(
			'teams',
			{ _and: [{ organization: { _eq: orgId } }, { name: { _eq: t.name } }] },
			{
				name: t.name,
				description: t.description,
				organization: orgId,
				active: true,
				status: 'published',
				focus: t.focus,
				goals: t.goals,
			},
			`team "${t.name}"`,
		);
		if (!team) continue;
		out[t.key] = team.id;

		// Attach users via junction (is_manager = true for the team lead)
		for (const idx of t.memberIdxs) {
			const userId = memberUserIds[idx];
			if (!userId) continue;
			await findOrCreate(
				'junction_directus_users_teams',
				{ _and: [{ teams_id: { _eq: team.id } }, { directus_users_id: { _eq: userId } }] },
				{ teams_id: team.id, directus_users_id: userId, is_manager: idx === t.managerIdx },
				`team member ${t.name} ← user[${idx}]`,
			);
		}
	}
	return out;
}

async function seedTeamGoals(teamIds: Record<string, string>): Promise<void> {
	const today = new Date();
	const future = (days: number) => {
		const d = new Date(today);
		d.setDate(d.getDate() + days);
		return d.toISOString().slice(0, 10);
	};
	const goals = [
		{ teamKey: 'creative', title: 'Ship Helios West brand system', description: 'Full delivery incl. collateral + signage.', target_date: future(30), progress: 65 },
		{ teamKey: 'creative', title: 'Redesign portfolio site', description: 'Internal marketing site refresh.', target_date: future(90), progress: 15 },
		{ teamKey: 'delivery', title: 'Launch Pinecrest portal soft release', description: 'Limited rollout to one clinic.', target_date: future(80), progress: 20 },
		{ teamKey: 'delivery', title: 'Reduce PM overhead by 10%', description: 'Internal process audit.', target_date: future(120), progress: 5 },
	];
	for (const g of goals) {
		const teamId = teamIds[g.teamKey];
		if (!teamId) continue;
		await findOrCreate(
			'team_goals',
			{ _and: [{ team: { _eq: teamId } }, { title: { _eq: g.title } }] },
			{
				team: teamId,
				title: g.title,
				description: g.description,
				target_date: g.target_date,
				progress: g.progress,
			},
			`team_goal "${g.title}"`,
		);
	}
}

async function seedMailingListsAndCampaign(
	orgId: string,
	contactIds: Record<string, string>,
): Promise<void> {
	const lists: Array<{ slug: string; name: string; description: string; emails: string[] }> = [
		{
			slug: 'agency-clients',
			name: 'Active Clients',
			description: 'Current client decision-makers.',
			emails: [
				'sonia@helios.example',
				'amara@meridian.example',
				'priya@pinecrest.example',
			],
		},
		{
			slug: 'agency-prospects',
			name: 'Prospects',
			description: 'Warm prospects + partners.',
			emails: [
				'marcus@northwind.example',
				'sana@northwind.example',
				'rae@driftwood.example',
				'owen@frey-gallery.example',
			],
		},
	];
	for (const l of lists) {
		const row = await findOrCreate<any>(
			'mailing_lists',
			{ _and: [{ organization: { _eq: orgId } }, { slug: { _eq: l.slug } }] },
			{
				name: l.name,
				slug: l.slug,
				description: l.description,
				organization: orgId,
				is_default: false,
				double_opt_in: false,
				subscriber_count: l.emails.length,
				status: 'published',
			},
			`mailing_list "${l.name}"`,
		);
		if (!row) continue;
		for (const email of l.emails) {
			const contactId = contactIds[email];
			if (!contactId) continue;
			await findOrCreate(
				'mailing_list_contacts',
				{ _and: [{ list_id: { _eq: row.id } }, { contact_id: { _eq: contactId } }] },
				{
					list_id: row.id,
					contact_id: contactId,
					subscribed: true,
					date_subscribed: new Date().toISOString(),
					source: 'demo-seed',
				},
				`list membership (${l.slug} ← ${email})`,
			);
		}
	}

	// One marketing campaign (goal-setting surface — not a sent email, but
	// enough to populate the Marketing Intelligence tab).
	await findOrCreate(
		'marketing_campaigns',
		{ _and: [{ organization: { _eq: orgId } }, { title: { _eq: 'Helios West opening — launch campaign' } }] },
		{
			title: 'Helios West opening — launch campaign',
			goal: 'Drive bookings for opening month. Target: 80% occupancy week-one.',
			status: 'active',
			type: 'campaign',
			organization: orgId,
			start_date: new Date().toISOString().slice(0, 10),
			end_date: new Date(Date.now() + 30 * 86_400_000).toISOString().slice(0, 10),
		},
		`marketing_campaign "Helios West opening"`,
	);
}

async function seedProposal(
	orgId: string,
	leadIds: number[],
	contactIds: Record<string, string>,
): Promise<void> {
	if (leadIds.length === 0) return;
	// Proposal on the proposal_sent lead (Northwind phase 2).
	const leadId = leadIds[3] ?? leadIds[0];
	const contactId = contactIds['sana@northwind.example'] ?? contactIds['marcus@northwind.example'];
	await findOrCreate(
		'proposals',
		{ _and: [{ organization: { _eq: orgId } }, { title: { _eq: 'Northwind Phase 2 — Leasing Campaign' } }] },
		{
			title: 'Northwind Phase 2 — Leasing Campaign',
			organization: orgId,
			lead: leadId,
			contact: contactId || null,
			total_value: 38_000,
			proposal_status: 'sent',
			date_sent: new Date().toISOString().slice(0, 10),
			valid_until: new Date(Date.now() + 21 * 86_400_000).toISOString().slice(0, 10),
			notes: 'Campaign creative + media plan + reporting.',
		},
		`proposal "Northwind Phase 2"`,
	);
}

async function seedChannel(
	orgId: string,
	projectIds: Record<string, string>,
	memberUserIds: string[],
): Promise<void> {
	const channel = await findOrCreate<any>(
		'channels',
		{ _and: [{ organization: { _eq: orgId } }, { name: { _eq: '#helios-launch' } }] },
		{
			name: '#helios-launch',
			description: 'Launch coordination for Helios West Hotel.',
			organization: orgId,
			project: projectIds['helios-west-hotel'] || null,
			status: 'published',
		},
		`channel "#helios-launch"`,
	);
	if (!channel) return;

	const messages = [
		'Opening ceremony locked for the 18th.',
		'Launch carousel assets in review — Naomi approved the interior shots.',
		'HEL-0042 paid. Phase 2 scope can kick off next week.',
		'Pinged Liv PR about embargoed press drops — Design Weekly + one trade title lined up.',
		'Booking flow QA in progress — mobile has a date-picker glitch on Safari.',
		'Shot list for the hero gallery locked with Ben Wu.',
		'Pushed latest hero copy to staging — review link in the doc.',
		'Sonia signed off on the final brand-system PDF.',
		'Launch runbook draft is up. Please eyeball by EOD.',
		'Next sync: Thursday 10am. Agenda in the pinned doc.',
	];
	// Rotate authors across the demo members so the channel looks lived-in.
	for (let i = 0; i < messages.length; i++) {
		const text = messages[i];
		const author = memberUserIds[i % memberUserIds.length];
		if (!author) continue;
		await findOrCreate(
			'messages',
			{ _and: [{ channel: { _eq: channel.id } }, { text: { _eq: text } }] },
			{ channel: channel.id, text, user_created: author, status: 'published' },
			`message #${i + 1}`,
		);
	}
}

// ─── Main ─────────────────────────────────────────────────────────────────

type Teammate = {
	email: string;
	firstName: string;
	lastName: string;
};

const TEAMMATES: Teammate[] = [
	{ email: 'demo-designer-1@earnest.guru', firstName: 'Casey', lastName: 'Designer' },
	{ email: 'demo-designer-2@earnest.guru', firstName: 'Jordan', lastName: 'Designer' },
	{ email: 'demo-pm@earnest.guru', firstName: 'Sam', lastName: 'PM' },
	{ email: 'demo-developer@earnest.guru', firstName: 'Alex', lastName: 'Developer' },
];

async function main() {
	console.log('============================================');
	console.log('  Earnest Demo (Agency) — org + users + seed');
	console.log('============================================');
	console.log(`Target: ${process.env.DIRECTUS_URL || 'http://localhost:8055'}\n`);

	await pingDirectus();

	console.log('--- org ---');
	const org = await ensureOrg();
	if (!org) process.exit(1);

	console.log('\n--- system roles ---');
	const roles = await ensureRoles(org.id, {
		admin: DEMO_ADMIN_PERMISSIONS,
		member: DEMO_MEMBER_PERMISSIONS,
	});
	if (!roles.admin || !roles.member) {
		console.error('Missing Admin or Member role id — aborting.');
		process.exit(1);
	}

	console.log('\n--- admin demo user ---');
	const adminUser = await ensureUser({
		email: DEMO_ADMIN_EMAIL,
		password: demoPassword,
		firstName: DEMO_ADMIN_FIRST,
		lastName: DEMO_ADMIN_LAST,
	});
	if (!adminUser) process.exit(1);

	console.log('\n--- admin membership ---');
	await ensureMembership(org.id, adminUser.id, roles.admin, 'agency demo → Admin');

	console.log('\n--- teammates ---');
	const teammateIds: string[] = [];
	for (const t of TEAMMATES) {
		// Teammates share the agency demo password so they can be logged
		// into separately if ever needed for QA. (Login surface stays
		// single-user — this is just provisioning.)
		const user = await ensureUser({
			email: t.email,
			password: demoPassword,
			firstName: t.firstName,
			lastName: t.lastName,
		});
		if (user) {
			teammateIds.push(user.id);
			await ensureMembership(org.id, user.id, roles.member, `teammate ${t.email}`);
		}
	}

	console.log('\n--- clients ---');
	const clientIds = await seedClients(org.id);

	console.log('\n--- contacts ---');
	const contactIds = await seedContacts(org.id, clientIds);

	console.log('\n--- contact_connections (partners) ---');
	await seedContactConnections(clientIds, contactIds);

	console.log('\n--- leads ---');
	const leadIds = await seedLeads(org.id, contactIds, clientIds, adminUser.id);

	console.log('\n--- projects ---');
	const projectIds = await seedProjects(org.id, clientIds);

	console.log('\n--- project events ---');
	const eventIds = await seedProjectEvents(projectIds);

	console.log('\n--- project tasks ---');
	await seedProjectTasks(projectIds, eventIds, teammateIds);

	console.log('\n--- products + invoices ---');
	const productId = await seedProduct();
	await seedInvoices(org.id, clientIds, productId);

	console.log('\n--- tickets ---');
	await seedTickets(org.id, projectIds, clientIds, teammateIds);

	console.log('\n--- teams ---');
	const teamIds = await seedTeams(org.id, teammateIds);

	console.log('\n--- team goals ---');
	await seedTeamGoals(teamIds);

	console.log('\n--- mailing lists + campaign ---');
	await seedMailingListsAndCampaign(org.id, contactIds);

	console.log('\n--- proposal ---');
	await seedProposal(org.id, leadIds, contactIds);

	console.log('\n--- channel + messages ---');
	await seedChannel(org.id, projectIds, [adminUser.id, ...teammateIds]);

	console.log('\n============================================');
	console.log('  Summary');
	console.log('============================================');
	console.log(`  Org ID:  ${org.id}`);
	console.log(`  Admin:   ${DEMO_ADMIN_EMAIL} (id=${adminUser.id})`);
	console.log(`  Teammates: ${TEAMMATES.map((t) => t.email).join(', ')}`);
	if (generatedPassword) {
		console.log('');
		console.log('  ⚠ Generated a new agency demo password. Save this to your env as');
		console.log('    DEMO_AGENCY_USER_PASSWORD — /api/auth/demo-agency-login reads it.');
		console.log(`    DEMO_AGENCY_USER_PASSWORD="${demoPassword}"`);
	} else {
		console.log('  Password: (from env DEMO_AGENCY_USER_PASSWORD)');
	}
	console.log('\nDone.');
}

main().catch((err) => {
	console.error('Setup failed:', err);
	process.exit(1);
});
