#!/usr/bin/env npx tsx
/**
 * Directus — Earnest Demo (Solo) org + user + seed data
 *
 * Provisions the solo-studio demo: one org, one Member-role user, a
 * believable slice of one-person-studio seed data. Anonymous visitors who
 * pick "Solo studio" on /try-demo land here.
 *
 * Idempotent: every create is guarded by a find-by-key check; re-running
 * the script never duplicates data.
 *
 * AI is capped via the existing org token budget (10K tokens/month + 3
 * scan credits/month). The Member role in this org has `ai_usage` bumped
 * to access+read+create so demo visitors can actually use Ask Earnest
 * (normal Member role has ai_usage disabled — the token budget is the
 * real cap).
 *
 * Usage:
 *   DEMO_USER_PASSWORD=<secret> pnpm tsx scripts/setup-demo-org.ts
 *
 * If DEMO_USER_PASSWORD is unset, the script generates one and prints it.
 * Save it to your env — /api/auth/demo-login reads the same variable.
 */

import 'dotenv/config';
import { DEFAULT_ROLE_PERMISSIONS } from '../shared/permissions';
import type { PermissionMatrix } from '../shared/permissions';
import {
	assertDirectusToken,
	assignTicketsToUser,
	backdateContacts,
	directusRequest,
	ensureMembership,
	ensureRoles,
	ensureUser,
	findOrCreate,
	findOne,
	generatePassword,
	pingDirectus,
	randomToken,
	seedDocumentBlocks,
	seedServiceTemplates,
	seedDemoProposal,
	seedDemoContracts,
	seedTodayAppointments,
	seedDemoServices,
	seedDemoProjects,
	seedTimeEntries,
	seedSocial,
	type ProjectSeed,
	type TimeEntrySeed,
} from './lib/demo-seed';

const DEMO_ORG_NAME = 'Earnest Demo — Solo';
const DEMO_ORG_SHORT = 'SOLO';
const DEMO_ORG_CODE = 'SOL'; // 3-letter code used as the invoice-code prefix.
const DEMO_ORG_SLUG = 'earnest-demo-solo'; // idempotency key after scripts/add-organizations-slug.ts runs.
const DEMO_USER_EMAIL = process.env.DEMO_USER_EMAIL || 'demo@earnest.guru';
const DEMO_USER_FIRST = 'Demo';
const DEMO_USER_LAST = 'Solo';
const DEMO_AI_TOKEN_LIMIT_MONTHLY = 10_000;
const DEMO_SCAN_LIMIT_MONTHLY = 3;
const DEMO_ORG_EMAIL = 'hello@earnest.guru';
const DEMO_ORG_PHONE = '(415) 555-0123';
const DEMO_ORG_ADDRESS = '548 Market St #62914\nSan Francisco, CA 94104';
const DEMO_ORG_WEBSITE = 'https://earnest.guru';

let demoPassword = process.env.DEMO_USER_PASSWORD || '';
let generatedPassword = false;
if (!demoPassword) {
	demoPassword = generatePassword();
	generatedPassword = true;
}

assertDirectusToken();

// Override Member.ai_usage for the demo org so visitors can chat with Earnest.
// Real-world cap is enforced by the org token budget, not the perm matrix.
const DEMO_MEMBER_PERMISSIONS: PermissionMatrix = {
	...DEFAULT_ROLE_PERMISSIONS.member,
	ai_usage: { access: true, read: true, create: true, update: false, delete: false },
};

async function ensureOrg(): Promise<any | null> {
	// Match by slug (stable URL-safe key). Fall back to legacy names so a
	// pre-slug org gets upgraded in place rather than duplicated.
	const existing =
		(await findOne<any>('organizations', { slug: { _eq: DEMO_ORG_SLUG } })) ||
		(await findOne<any>('organizations', { name: { _eq: DEMO_ORG_NAME } })) ||
		(await findOne<any>('organizations', { name: { _eq: 'Earnest Demo' } }));
	if (existing) {
		console.log(`  [skip] org "${DEMO_ORG_NAME}" (id=${existing.id})`);
		await directusRequest(`/items/organizations/${existing.id}`, 'PATCH', {
			name: DEMO_ORG_NAME,
			slug: DEMO_ORG_SLUG,
			short_name: DEMO_ORG_SHORT,
			code: DEMO_ORG_CODE,
			ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
			scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
			email: DEMO_ORG_EMAIL,
			phone: DEMO_ORG_PHONE,
			address: DEMO_ORG_ADDRESS,
			website: DEMO_ORG_WEBSITE,
		});
		return existing;
	}
	const res = await directusRequest<any>('/items/organizations', 'POST', {
		name: DEMO_ORG_NAME,
		slug: DEMO_ORG_SLUG,
		short_name: DEMO_ORG_SHORT,
		code: DEMO_ORG_CODE,
		status: 'published',
		active: true,
		plan: 'solo',
		ai_token_limit_monthly: DEMO_AI_TOKEN_LIMIT_MONTHLY,
		ai_tokens_used_this_period: 0,
		scan_credits_limit_monthly: DEMO_SCAN_LIMIT_MONTHLY,
		scans_used_this_period: 0,
		email: DEMO_ORG_EMAIL,
		phone: DEMO_ORG_PHONE,
		address: DEMO_ORG_ADDRESS,
		website: DEMO_ORG_WEBSITE,
		notes: 'Public solo demo workspace. Seed regenerated by scripts/setup-demo-org.ts.',
	});
	if (!res.ok) {
		console.error(`  [fail] create org: ${res.error}`);
		return null;
	}
	console.log(`  [ok]   org "${DEMO_ORG_NAME}" (id=${res.data?.id})`);
	return res.data;
}

// ─── Seed data (solo-studio flavor) ──────────────────────────────────────

const CLIENT_SEEDS = [
	{ key: 'helios-studio', name: 'Helios Studio', industry: 'Hospitality', website: 'https://helios.example', account_state: 'active', code: 'HEL' },
	{ key: 'meridian-law', name: 'Meridian Law Group', industry: 'Legal', website: 'https://meridian.example', account_state: 'prospect', code: 'MER' },
];

async function seedClients(orgId: string): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CLIENT_SEEDS) {
		const row = await findOrCreate<any>(
			'clients',
			{ _and: [{ organization: { _eq: orgId } }, { slug: { _eq: c.key } }] },
			{
				name: c.name,
				slug: c.key,
				organization: orgId,
				industry: c.industry,
				website: c.website,
				account_state: c.account_state,
				code: c.code,
				status: 'published',
				notes: 'Solo demo seed.',
			},
			`client "${c.name}"`,
		);
		if (row) ids[c.key] = row.id;
	}
	return ids;
}

const CONTACT_SEEDS: Array<{
	first_name: string;
	last_name: string;
	email: string;
	title: string;
	company: string;
	category: 'client' | 'prospect' | 'partner' | 'architect' | 'developer' | 'hospitality' | 'media';
	clientKey?: string;
	notes?: string;
}> = [
	{ first_name: 'Sonia', last_name: 'Reyes', email: 'sonia@helios.example', title: 'Owner', company: 'Helios Studio', category: 'client', clientKey: 'helios-studio', notes: 'Primary contact at Helios.' },
	{ first_name: 'David', last_name: 'Park', email: 'david@helios.example', title: 'Head of Operations', company: 'Helios Studio', category: 'client', clientKey: 'helios-studio' },
	{ first_name: 'Amara', last_name: 'Okafor', email: 'amara@meridian.example', title: 'Managing Partner', company: 'Meridian Law Group', category: 'prospect', clientKey: 'meridian-law' },
	{ first_name: 'Julia', last_name: 'Holt', email: 'julia@atlas.example', title: 'VP Marketing', company: 'Atlas Fintech', category: 'prospect' },
	{ first_name: 'Rae', last_name: 'Nakamura', email: 'rae.nakamura@example.com', title: 'Co-Founder', company: 'Driftwood Roasters', category: 'prospect' },
	{ first_name: 'Elena', last_name: 'Vargas', email: 'elena@vargasrealty.example', title: 'Broker', company: 'Vargas Realty', category: 'partner', notes: 'Referral partner.' },
];

async function seedContacts(
	orgId: string,
	clientIds: Record<string, string>,
): Promise<Record<string, string>> {
	const ids: Record<string, string> = {};
	for (const c of CONTACT_SEEDS) {
		const clientId = c.clientKey ? clientIds[c.clientKey] : null;
		const contact = await findOrCreate<any>(
			'contacts',
			{
				_and: [
					{ email: { _eq: c.email } },
					{ organizations: { organizations_id: { _eq: orgId } } },
				],
			},
			{
				first_name: c.first_name,
				last_name: c.last_name,
				email: c.email,
				title: c.title,
				company: c.company,
				category: c.category,
				client: clientId,
				source: 'demo',
				status: 'published',
				notes: c.notes || null,
				email_subscribed: true,
				unsubscribe_token: randomToken(),
			},
			`contact ${c.first_name} ${c.last_name}`,
		);
		if (contact) {
			ids[c.email] = contact.id;
			await findOrCreate(
				'contacts_organizations',
				{ _and: [{ contacts_id: { _eq: contact.id } }, { organizations_id: { _eq: orgId } }] },
				{ contacts_id: contact.id, organizations_id: orgId },
				`contact junction (${c.first_name})`,
			);
		}
	}
	return ids;
}

async function seedLeads(
	orgId: string,
	contactIds: Record<string, string>,
	clientIds: Record<string, string>,
): Promise<number[]> {
	const leads = [
		{
			contactEmail: 'julia@atlas.example',
			stage: 'contacted',
			priority: 'medium',
			source: 'website',
			source_details: 'Site form.',
			estimated_value: 42_000,
			project_type: 'Marketing site redesign',
			timeline: '3-6 months',
			tags: ['rfp'],
			notes: 'First intro call scheduled for next week.',
		},
		{
			contactEmail: 'rae.nakamura@example.com',
			stage: 'won',
			priority: 'medium',
			source: 'referral',
			source_details: 'Existing client referred them.',
			estimated_value: 28_000,
			actual_value: 31_500,
			project_type: 'Rebrand + packaging',
			timeline: 'flexible',
			closed_date: new Date().toISOString().slice(0, 10),
			resulting_client_key: 'helios-studio',
			tags: ['hot'],
			notes: 'Contracts signed.',
		},
	];
	const created: number[] = [];
	for (const l of leads) {
		const relatedContact = contactIds[l.contactEmail];
		const resultingClient = (l as any).resulting_client_key ? clientIds[(l as any).resulting_client_key] : null;
		if (!relatedContact) continue;
		const row = await findOrCreate<any>(
			'leads',
			{
				_and: [
					{ organization: { _eq: orgId } },
					{ related_contact: { _eq: relatedContact } },
					{ project_type: { _eq: l.project_type } },
				],
			},
			{
				organization: orgId,
				related_contact: relatedContact,
				stage: l.stage,
				priority: l.priority,
				source: l.source,
				source_details: l.source_details,
				estimated_value: l.estimated_value,
				actual_value: (l as any).actual_value ?? null,
				project_type: l.project_type,
				timeline: l.timeline,
				tags: l.tags,
				notes: l.notes,
				closed_date: (l as any).closed_date ?? null,
				resulting_client: resultingClient,
				status: 'published',
			},
			`lead (${l.contactEmail} / ${l.stage})`,
		);
		if (row) created.push(row.id);
	}
	return created;
}

/**
 * Build the solo demo's project list. Three projects with mixed statuses
 * + a spread of event types (Design / Content / Timeline / Hours / Financial)
 * so the Project Timeline gantt on /command-center renders the full
 * Clean-Gantt color palette (and the bars vary in opacity by status).
 *
 * Helios anchors most of the workspace narrative — kept as the primary
 * In-Progress project. Meridian closes a recently-completed engagement so
 * the gantt shows a faded/completed lane. Driftwood is a Scheduled lane
 * — the rebrand teed up by the won "rae.nakamura" lead.
 */
function buildSoloProjectSeeds(clientIds: Record<string, string>): ProjectSeed[] {
	return [
		{
			key: 'helios-launch',
			title: 'Helios West Hotel Launch',
			description: 'Brand rollout + launch campaign.',
			clientId: clientIds['helios-studio'] ?? null,
			serviceName: 'Brand & Identity',
			status: 'In Progress',
			contractValue: 140_000,
			startDayOffset: -45,
			events: [
				{ title: 'Discovery + stakeholder interviews', type: 'General', status: 'Completed', dayOffset: -42, durationDays: 5 },
				{ title: 'Brand system — v1 concepts', type: 'Design', status: 'Completed', dayOffset: -28, durationDays: 10 },
				{ title: 'Launch campaign content', type: 'Content', status: 'Active', dayOffset: -7, durationDays: 14 },
				{ title: 'Phase 1 invoice', type: 'Financial', status: 'Completed', dayOffset: -10, durationDays: 1, is_milestone: true },
				{ title: 'Opening ceremony', type: 'Timeline', status: 'Scheduled', dayOffset: 21, is_milestone: true },
			],
		},
		{
			key: 'meridian-refresh',
			title: 'Meridian Site Refresh',
			description: 'Marketing site redesign with updated practice-area templates.',
			clientId: clientIds['meridian-law'] ?? null,
			serviceName: 'Web & Digital',
			status: 'Completed',
			contractValue: 38_000,
			startDayOffset: -90,
			events: [
				{ title: 'Kickoff + content inventory', type: 'General', status: 'Completed', dayOffset: -82, durationDays: 4 },
				{ title: 'Practice-page wireframes', type: 'Design', status: 'Completed', dayOffset: -65, durationDays: 12 },
				{ title: 'Build + content load', type: 'Content', status: 'Completed', dayOffset: -40, durationDays: 18 },
				{ title: 'Site launch', type: 'Timeline', status: 'Completed', dayOffset: -15, is_milestone: true },
			],
		},
		{
			key: 'driftwood-rebrand',
			title: 'Driftwood Roasters Rebrand',
			description: 'Wordmark + packaging system for the new flagship line.',
			clientId: clientIds['helios-studio'] ?? null, // narrative bridge — close enough for demo
			serviceName: 'Brand & Identity',
			status: 'Scheduled',
			contractValue: 31_500,
			startDayOffset: 14,
			events: [
				{ title: 'Discovery week', type: 'General', status: 'Scheduled', dayOffset: 14, durationDays: 5 },
				{ title: 'Identity directions', type: 'Design', status: 'Scheduled', dayOffset: 25, durationDays: 10 },
				{ title: 'Packaging concepts', type: 'Design', status: 'Scheduled', dayOffset: 40, durationDays: 14 },
				{ title: 'Production hours allocation', type: 'Hours', status: 'Scheduled', dayOffset: 55, durationDays: 20 },
				{ title: 'Launch deliverables due', type: 'Timeline', status: 'Scheduled', dayOffset: 78, is_milestone: true },
			],
		},
	];
}

async function seedProduct(): Promise<string | null> {
	const row = await findOrCreate<any>(
		'products',
		{ name: { _eq: 'Demo Services' } },
		{ name: 'Demo Services', status: 'published', description: 'Generic line item for demo invoices.' },
		`product "Demo Services"`,
	);
	return row?.id ?? null;
}

async function seedInvoice(
	orgId: string,
	clientIds: Record<string, string>,
	productId: string | null,
): Promise<void> {
	const today = new Date();
	const addDays = (d: Date, days: number) => {
		const nd = new Date(d);
		nd.setDate(nd.getDate() + days);
		return nd;
	};
	const iso = (d: Date) => d.toISOString().slice(0, 10);

	const client = clientIds['helios-studio'];
	if (!client) return;

	// Format matches app/composables/useInvoices.ts::generateInvoiceCode:
	//   INV-{ORG_CODE}-{CLIENT_CODE}-{YEAR}-{NNNN}
	const year = today.getFullYear();
	const invoiceCode = `INV-${DEMO_ORG_CODE}-HEL-${year}-0042`;

	const row = await findOrCreate<any>(
		'invoices',
		{ _and: [{ bill_to: { _eq: orgId } }, { invoice_code: { _eq: invoiceCode } }] },
		{
			bill_to: orgId,
			client,
			invoice_code: invoiceCode,
			status: 'paid',
			invoice_date: iso(addDays(today, -30)),
			due_date: iso(addDays(today, -15)),
			total_amount: 18_500,
			note: 'Helios West Hotel — brand system phase 1.',
		},
		`invoice ${invoiceCode}`,
	);
	if (row && productId) {
		await findOrCreate(
			'line_items',
			{ _and: [{ invoice_id: { _eq: row.id } }, { description: { _eq: 'Brand system — phase 1' } }] },
			{
				invoice_id: row.id,
				product: productId,
				description: 'Brand system — phase 1',
				rate: 18_500,
				quantity: 1,
				amount: 18_500,
			},
			`line_item ${invoiceCode}`,
		);
	}
}

/**
 * Upsert one marketing_campaigns row. PATCH on re-run so plan_data refreshes
 * when the seed file changes — find/create-only would freeze old content.
 */
async function upsertMarketingPlan(
	orgId: string,
	title: string,
	payload: Record<string, any>,
	label: string,
): Promise<void> {
	const existing = await findOne<any>('marketing_campaigns', {
		_and: [{ organization: { _eq: orgId } }, { title: { _eq: title } }],
	});
	if (existing) {
		const res = await directusRequest(
			`/items/marketing_campaigns/${existing.id}`,
			'PATCH',
			payload,
		);
		if (!res.ok) {
			console.error(`  [fail] update ${label}: ${res.error}`);
			return;
		}
		console.log(`  [ok]   ${label} (refreshed plan_data, id=${existing.id})`);
		return;
	}
	const res = await directusRequest<any>('/items/marketing_campaigns', 'POST', {
		...payload,
		title,
		organization: orgId,
	});
	if (!res.ok) {
		console.error(`  [fail] create ${label}: ${res.error}`);
		return;
	}
	console.log(`  [ok]   ${label} (id=${(res.data as any)?.id})`);
}

async function seedMarketingPlans(orgId: string): Promise<void> {
	const today = new Date();
	const iso = (offsetDays: number) => {
		const d = new Date(today);
		d.setDate(d.getDate() + offsetDays);
		return d.toISOString().slice(0, 10);
	};

	// Solo-studio dashboard — small audience, modest cadence, real opportunities.
	const dashboardPlan = {
		healthScore: 64,
		healthBreakdown: {
			contentConsistency: 58,
			audienceGrowth: 70,
			engagement: 66,
			emailPerformance: 62,
		},
		contentVelocity: {
			postsPerWeek: 2,
			emailsPerMonth: 1,
			trend: 'up' as const,
		},
		audienceGrowth: {
			followers: 1240,
			subscribers: 186,
			contacts: 28,
			trend: 'up' as const,
		},
		insights: [
			{
				type: 'strength',
				title: 'Referral-driven leads are converting fast',
				description: 'The Driftwood Roasters win closed in under three weeks from intro. Your referral network is the highest-leverage channel right now.',
				priority: 'medium',
				actionable: false,
				channel: 'referrals',
			},
			{
				type: 'opportunity',
				title: 'Helios launch is a portfolio-piece moment',
				description: 'A short case-study post + one process reel could land you in front of two hospitality prospects in the pipeline. Time-box it to two hours.',
				priority: 'high',
				actionable: true,
				channel: 'content',
				link: '/marketing',
			},
			{
				type: 'weakness',
				title: 'Email cadence is too thin to compound',
				description: 'One newsletter every six weeks lets relationships go cold between sends. A monthly cadence is the floor for a one-person studio.',
				priority: 'medium',
				actionable: true,
				channel: 'email',
			},
			{
				type: 'action',
				title: 'Follow up with Julia Holt this week',
				description: 'Atlas Fintech intro call was scheduled then went quiet. A short, specific re-ping (not a generic "checking in") is overdue.',
				priority: 'high',
				actionable: true,
				channel: 'email',
				link: '/leads',
			},
		],
		recommendations: [
			{
				title: 'Ship a Helios launch reel',
				description: '60-second IG reel — three brand directions, the chosen one, the launch hero shot. Reuse Figma frames + opening-day photo.',
				channel: 'social',
				effort: 'low' as const,
				impact: 'high' as const,
			},
			{
				title: 'Move email to monthly',
				description: 'Pick one slot (first Tuesday). Three short paragraphs: project moment, perspective, ask. Drafts compound after issue 3.',
				channel: 'email',
				effort: 'low' as const,
				impact: 'medium' as const,
			},
			{
				title: 'Ask three referral partners for an intro',
				description: 'Vargas Realty, plus two more. Specific ask beats open-ended — name the prospect type and the tag-along value.',
				channel: 'referrals',
				effort: 'low' as const,
				impact: 'high' as const,
			},
		],
	};

	await upsertMarketingPlan(
		orgId,
		'Solo Studio — Marketing Health Snapshot',
		{
			goal: 'See where the studio\'s marketing actually stands and what to do this week.',
			status: 'active',
			type: 'dashboard',
			plan_data: dashboardPlan,
			start_date: iso(-30),
			end_date: iso(0),
		},
		'marketing dashboard "Solo Studio Health Snapshot"',
	);

	// Solo campaign — Helios launch from a small-studio angle.
	const campaignPlan = {
		campaignName: 'Helios Launch — Studio Showcase',
		objective: 'Use the Helios West launch as a portfolio-piece moment that lands two hospitality prospects in the pipeline within 30 days.',
		timeline: [
			{
				week: 1,
				activities: [
					{ channel: 'social', action: 'Process post — three concept directions', details: 'IG carousel showing the three brand directions and which one Helios picked. Frame the work, not the studio.' },
					{ channel: 'content', action: 'One-page case study draft', details: 'PDF with the brief, the work, and one outcome quote. Save for follow-ups.' },
					{ channel: 'email', action: 'Newsletter restart', details: 'Short note: "We just shipped this." Lead with the work, end with one ask.' },
				],
			},
			{
				week: 2,
				activities: [
					{ channel: 'social', action: 'Behind-the-scenes reel', details: '45 seconds — sketches, swatches, the final brand mark on the door. Vertical video.' },
					{ channel: 'email', action: 'Send case study to two warm contacts', details: 'Personal one-line intros to Julia Holt + Rae Nakamura. Not a blast.' },
				],
			},
			{
				week: 3,
				activities: [
					{ channel: 'social', action: 'Hero shot post', details: 'Single image, tight caption. The launch photograph. Cross-post to LinkedIn.' },
					{ channel: 'referrals', action: 'Ping three partners with the case study', details: 'Vargas Realty + two others. "If you know a hospitality founder thinking about brand, this is the work."' },
				],
			},
			{
				week: 4,
				activities: [
					{ channel: 'content', action: 'Reflection post on the agency site', details: 'A short essay — what shipping Helios taught the studio. Long-form, not a portfolio listing.' },
					{ channel: 'email', action: 'Newsletter #2', details: 'Three-paragraph wrap: a moment, a perspective, an ask. Builds the cadence.' },
				],
			},
		],
		emailSequence: [
			{ day: 1, subject: 'We just shipped Helios West', keyMessage: 'Restart the newsletter with a launch story — three paragraphs, one image.', cta: 'See the work', segment: 'All subscribers' },
			{ day: 7, subject: 'Thinking of you', keyMessage: 'One-line personal note + the case-study PDF. Sent to Julia + Rae individually.', cta: 'Open the PDF', segment: 'Warm prospects' },
			{ day: 28, subject: 'A short reflection on shipping', keyMessage: 'Studio-perspective essay — what we learned, what we\'d redo.', cta: 'Read the reflection', segment: 'All subscribers' },
		],
		socialPosts: [
			{ platform: 'Instagram', content: 'Three concepts in. The one Helios chose — and why. Brand process, four frames.', hashtags: ['branddesign', 'studio', 'process'], timing: 'Week 1 — Tue 10am' },
			{ platform: 'Instagram', content: 'Behind the scenes on Helios. 45 seconds, sketch to door.', hashtags: ['behindthescenes', 'branddesign', 'studio'], timing: 'Week 2 — Wed 11am' },
			{ platform: 'LinkedIn', content: 'A note on shipping a brand system in 14 weeks for a hotel that just opened. Three calls we\'d make again.', hashtags: ['branding', 'hospitality', 'studiolife'], timing: 'Week 3 — Tue 8am' },
			{ platform: 'Instagram', content: 'Helios West, opening morning. One image, no caption needed.', hashtags: ['helioswest', 'hospitality', 'newhotel'], timing: 'Week 3 — Sat 9am' },
		],
		kpis: [
			{ metric: 'New hospitality leads', target: '2', rationale: 'The whole campaign exists to land two warm conversations. Anything else is bonus.' },
			{ metric: 'IG saves on the case study post', target: '40+', rationale: 'Saves > likes for B2B content — saves predict portfolio-tab visits.' },
			{ metric: 'Newsletter open rate', target: '45%', rationale: 'Restart-issue benchmark. Drops next month, climbs by issue 3.' },
		],
	};

	await upsertMarketingPlan(
		orgId,
		'Helios Launch — Studio Showcase',
		{
			goal: 'Use the Helios launch to bring in two hospitality prospects this month.',
			status: 'active',
			type: 'campaign',
			plan_data: campaignPlan,
			start_date: iso(0),
			end_date: iso(30),
		},
		'marketing campaign "Helios Launch — Studio Showcase"',
	);
}

async function seedQuickTasks(
	orgId: string,
	userId: string,
	projectIds: Record<string, string>,
	clientIds: Record<string, string>,
): Promise<void> {
	// Mix of schedules + statuses + priorities so the /tasks page shows a
	// believable mid-week working state: Today has 4 (one in_progress), This
	// Week has 4, Later has 3, and 2 completed land in the "Done" bucket.
	const tasks: Array<{
		title: string;
		description?: string;
		schedule: 'today' | 'this_week' | 'later';
		priority: 'low' | 'medium' | 'high' | 'urgent';
		status: 'new' | 'in_progress' | 'completed';
		category: 'quick' | 'ticket' | 'project';
		clientKey?: string;
		projectKey?: string;
		dueDayOffset?: number;
		assignToSelf?: boolean;
	}> = [
		// — Today —
		{ title: 'Reply to Julia Holt re: intro call', description: 'She asked about timeline + team size — pull a recent case study.', schedule: 'today', priority: 'high', status: 'new', category: 'quick', dueDayOffset: 0, assignToSelf: true },
		{ title: 'Send Helios West v2 brand deck', description: 'Final hex codes + the updated wordmark lockup.', schedule: 'today', priority: 'urgent', status: 'in_progress', category: 'project', clientKey: 'helios-studio', projectKey: 'helios-launch', dueDayOffset: 0, assignToSelf: true },
		{ title: 'Confirm HEL-0042 payment received', schedule: 'today', priority: 'medium', status: 'completed', category: 'project', clientKey: 'helios-studio', projectKey: 'helios-launch' },
		{ title: 'Block 60 min for Driftwood concept review', schedule: 'today', priority: 'medium', status: 'new', category: 'quick', dueDayOffset: 0, assignToSelf: true },

		// — This week —
		{ title: 'Draft launch carousel copy', description: '4 frames, 50 words each — open with the moment, close with the booking link.', schedule: 'this_week', priority: 'medium', status: 'in_progress', category: 'project', clientKey: 'helios-studio', projectKey: 'helios-launch', dueDayOffset: 3, assignToSelf: true },
		{ title: 'Pull Q1 utilization report for studio review', schedule: 'this_week', priority: 'low', status: 'new', category: 'quick', dueDayOffset: 4, assignToSelf: true },
		{ title: 'Refresh Meridian wireframe annotations', schedule: 'this_week', priority: 'medium', status: 'new', category: 'project', clientKey: 'meridian-law', projectKey: 'meridian-refresh', dueDayOffset: 5, assignToSelf: true },
		{ title: 'Outline reflection essay — "shipping a brand in 14 weeks"', schedule: 'this_week', priority: 'low', status: 'new', category: 'quick', dueDayOffset: 6, assignToSelf: true },

		// — Later —
		{ title: 'Schedule Driftwood photographer (Ben Wu)', schedule: 'later', priority: 'medium', status: 'new', category: 'project', clientKey: 'helios-studio', projectKey: 'driftwood-rebrand', assignToSelf: true },
		{ title: 'Audit referral partner list — Q3 outreach', schedule: 'later', priority: 'low', status: 'new', category: 'quick', assignToSelf: true },
		{ title: 'Prep Helios case study PDF for portfolio', schedule: 'later', priority: 'medium', status: 'new', category: 'project', clientKey: 'helios-studio', projectKey: 'helios-launch', assignToSelf: true },

		// — Recently completed —
		{ title: 'Confirm Atlas intro time on Calendly', schedule: 'today', priority: 'high', status: 'completed', category: 'quick' },
		{ title: 'Sign Helios MSA renewal', schedule: 'this_week', priority: 'high', status: 'completed', category: 'project', clientKey: 'helios-studio' },
	];

	const todayIso = (offset = 0) => {
		const d = new Date();
		d.setHours(0, 0, 0, 0);
		d.setDate(d.getDate() + offset);
		return d.toISOString().slice(0, 10);
	};

	for (const t of tasks) {
		const projectId = t.projectKey ? projectIds[t.projectKey] ?? null : null;
		const clientId = t.clientKey ? clientIds[t.clientKey] ?? null : null;
		const due = typeof t.dueDayOffset === 'number' ? todayIso(t.dueDayOffset) : null;
		const completedAt = t.status === 'completed' ? new Date().toISOString() : null;
		const row = await findOrCreate<any>(
			'tasks',
			{ _and: [{ organization_id: { _eq: orgId } }, { title: { _eq: t.title } }] },
			{
				title: t.title,
				description: t.description ?? null,
				organization_id: orgId,
				project_id: projectId,
				client_id: clientId,
				schedule: t.schedule,
				priority: t.priority,
				status: t.status,
				category: t.category,
				due_date: due,
				date_completed: completedAt,
			},
			`task "${t.title}"`,
		);
		// Assign to demo user so /tasks "Assigned to Me" tab is non-empty.
		if (row && t.assignToSelf) {
			await findOrCreate(
				'tasks_directus_users',
				{ _and: [{ tasks_id: { _eq: row.id } }, { directus_users_id: { _eq: userId } }] },
				{ tasks_id: row.id, directus_users_id: userId },
				`task assignee (${t.title})`,
			);
		}
	}
}

/**
 * Build the solo demo's time-tracker entries. Anchored to the current week
 * via dayOffset (-5 → 0 covers Mon–today on most days). One entry stays
 * `running` so the timer dock + Time Tracker header show an active session.
 */
function buildSoloTimeEntries(): TimeEntrySeed[] {
	return [
		// 5 days ago
		{ key: 'helios-discovery-notes', description: 'Helios — discovery notes write-up', dayOffset: -5, edtStartHour: 9, durationMinutes: 90, projectKey: 'helios-launch', clientKey: 'helios-studio', billable: true, hourlyRate: 175 },
		{ key: 'meridian-redirect-map', description: 'Meridian — redirect map QA', dayOffset: -5, edtStartHour: 14, durationMinutes: 75, projectKey: 'meridian-refresh', clientKey: 'meridian-law', billable: true, hourlyRate: 175 },
		// 4 days ago
		{ key: 'helios-brand-refinement', description: 'Helios — brand v2 refinement', dayOffset: -4, edtStartHour: 10, durationMinutes: 150, projectKey: 'helios-launch', clientKey: 'helios-studio', billable: true, hourlyRate: 175 },
		// 3 days ago
		{ key: 'studio-newsletter', description: 'Studio newsletter draft', dayOffset: -3, edtStartHour: 8, durationMinutes: 45, billable: false },
		{ key: 'helios-launch-copy', description: 'Helios — launch carousel copy', dayOffset: -3, edtStartHour: 13, durationMinutes: 120, projectKey: 'helios-launch', clientKey: 'helios-studio', billable: true, hourlyRate: 175 },
		// 2 days ago
		{ key: 'driftwood-research', description: 'Driftwood — packaging benchmark scan', dayOffset: -2, edtStartHour: 11, durationMinutes: 60, projectKey: 'driftwood-rebrand', billable: true, hourlyRate: 175 },
		{ key: 'meridian-content-review', description: 'Meridian — practice-area content review', dayOffset: -2, edtStartHour: 15, durationMinutes: 90, projectKey: 'meridian-refresh', clientKey: 'meridian-law', billable: true, hourlyRate: 175 },
		// Yesterday
		{ key: 'helios-photo-direction', description: 'Helios — opening photoshoot direction', dayOffset: -1, edtStartHour: 9, durationMinutes: 105, projectKey: 'helios-launch', clientKey: 'helios-studio', billable: true, hourlyRate: 175 },
		{ key: 'studio-admin', description: 'Studio admin — invoicing + email', dayOffset: -1, edtStartHour: 16, durationMinutes: 30, billable: false },
		// Today
		{ key: 'helios-launch-prep', description: 'Helios — launch ceremony prep', dayOffset: 0, edtStartHour: 9, durationMinutes: 60, projectKey: 'helios-launch', clientKey: 'helios-studio', billable: true, hourlyRate: 175 },
		// Today — running timer (no end_time, status='running'). The dock
		// will show an active session for the screenshot.
		{ key: 'driftwood-concept-pass', description: 'Driftwood — concept pass 1', dayOffset: 0, edtStartHour: 11, durationMinutes: 45, projectKey: 'driftwood-rebrand', billable: true, hourlyRate: 175, running: true },
	];
}

// ─── Main ─────────────────────────────────────────────────────────────────

async function main() {
	console.log('=========================================');
	console.log('  Earnest Demo (Solo) — org + user + seed');
	console.log('=========================================');
	console.log(`Target: ${process.env.DIRECTUS_URL || 'http://localhost:8055'}\n`);

	await pingDirectus();

	console.log('--- org ---');
	const org = await ensureOrg();
	if (!org) process.exit(1);

	console.log('\n--- system roles ---');
	const roles = await ensureRoles(org.id, { member: DEMO_MEMBER_PERMISSIONS });
	if (!roles.member) {
		console.error('No Member role id — aborting.');
		process.exit(1);
	}

	console.log('\n--- demo user ---');
	const user = await ensureUser({
		email: DEMO_USER_EMAIL,
		password: demoPassword,
		firstName: DEMO_USER_FIRST,
		lastName: DEMO_USER_LAST,
	});
	if (!user) process.exit(1);

	console.log('\n--- membership ---');
	await ensureMembership(org.id, user.id, roles.member, 'solo demo → Member');

	console.log('\n--- clients ---');
	const clientIds = await seedClients(org.id);

	console.log('\n--- contacts ---');
	const contactIds = await seedContacts(org.id, clientIds);

	console.log('\n--- backdate contacts (audience growth chart) ---');
	await backdateContacts(Object.values(contactIds));

	console.log('\n--- leads ---');
	const leadIds = await seedLeads(org.id, contactIds, clientIds);

	console.log('\n--- services (color palette for Project Timeline) ---');
	const serviceIds = await seedDemoServices();

	console.log('\n--- projects + events (mixed status for Clean Gantt) ---');
	const projectIds = await seedDemoProjects({
		orgId: org.id,
		projects: buildSoloProjectSeeds(clientIds),
		serviceIds,
	});
	const projectId = projectIds['helios-launch'] ?? null;

	console.log('\n--- product + invoice ---');
	const productId = await seedProduct();
	await seedInvoice(org.id, clientIds, productId);

	console.log('\n--- quick tasks ---');
	await seedQuickTasks(org.id, user.id, projectIds, clientIds);

	console.log('\n--- time entries (this week + running timer) ---');
	await seedTimeEntries({
		orgId: org.id,
		userId: user.id,
		clientIds,
		projectIds,
		entries: buildSoloTimeEntries(),
	});

	console.log('\n--- marketing plans (dashboard + campaign) ---');
	await seedMarketingPlans(org.id);

	console.log('\n--- document_blocks library ---');
	const blockIds = await seedDocumentBlocks(org.id);

	console.log('\n--- service_templates library ---');
	await seedServiceTemplates(org.id);

	console.log('\n--- proposal (composed blocks) ---');
	// Lead 0 = Atlas Fintech (contacted, in active pipeline) — natural fit
	// for an in-flight proposal screenshot.
	const proposalId = await seedDemoProposal({
		orgId: org.id,
		leadId: leadIds[0] ?? null,
		contactId: contactIds['julia@atlas.example'] ?? null,
		blockIds,
		title: 'Atlas Fintech — Marketing Site Redesign',
		totalValue: 42_000,
		intro: {
			heading: 'Marketing Site Redesign',
			content:
				'Prepared for **Atlas Fintech** by **Earnest Demo**.\n\nThis proposal covers strategy, design, and build for an 8-page marketing site over an estimated 8-week engagement.',
		},
	});

	console.log('\n--- contracts ---');
	// Signed contract on the won lead (Helios) — narrative matches "Contracts
	// signed." in the lead notes.
	await seedDemoContracts({
		orgId: org.id,
		leadId: leadIds[1] ?? null,
		contactId: contactIds['rae.nakamura@example.com'] ?? null,
		proposalId: null,
		blockIds,
		contracts: [
			{
				title: 'Helios Studio — Master Services Agreement',
				contract_status: 'signed',
				total_value: 31_500,
				signer: { name: 'Rae Nakamura', email: 'rae.nakamura@example.com' },
			},
		],
	});
	// Unsigned contract on the active Atlas lead, linked to the proposal
	// above — completes the proposal → contract flow visible in the demo.
	await seedDemoContracts({
		orgId: org.id,
		leadId: leadIds[0] ?? null,
		contactId: contactIds['julia@atlas.example'] ?? null,
		proposalId,
		blockIds,
		contracts: [
			{
				title: 'Atlas Fintech — Statement of Work',
				contract_status: 'sent',
				total_value: 42_000,
			},
		],
	});

	console.log("\n--- today's appointments ---");
	await seedTodayAppointments({
		userId: user.id,
		contactId: contactIds['julia@atlas.example'] ?? null,
		leadId: leadIds[0] ?? null,
	});

	console.log('\n--- ticket assignees (so /tasks "Assigned to Me" tab fills) ---');
	await assignTicketsToUser(org.id, user.id);

	await seedSocial({
		orgId: org.id,
		assignments: [
			{ clientId: null, clientName: 'House', platforms: ['instagram', 'linkedin'] },
			{ clientId: clientIds['helios-studio'] ?? null, clientName: 'Helios Studio', platforms: ['instagram'] },
		],
		postCount: 6,
	});

	console.log('\n=========================================');
	console.log('  Summary');
	console.log('=========================================');
	console.log(`  Org ID:  ${org.id}`);
	console.log(`  User ID: ${user.id}`);
	console.log(`  Email:   ${DEMO_USER_EMAIL}`);
	if (generatedPassword) {
		console.log('');
		console.log('  ⚠ Generated a new demo password. Save this to your env as');
		console.log('    DEMO_USER_PASSWORD — /api/auth/demo-login reads it on every request.');
		console.log(`    DEMO_USER_PASSWORD="${demoPassword}"`);
	} else {
		console.log('  Password: (from env DEMO_USER_PASSWORD)');
	}
	console.log('\nDone.');
}

main().catch((err) => {
	console.error('Setup failed:', err);
	process.exit(1);
});
