#!/usr/bin/env npx tsx
/**
 * video_meetings — Transcription + AI Summary fields
 *
 * Adds the columns the Daily transcription pipeline + AI summary endpoint write to.
 *
 *   transcript_id          string  — Daily.co transcript handle
 *   transcript_text        text    — joined plain-text transcript (speaker-labelled)
 *   transcript_url         string  — Daily's permanent download URL
 *   summary                text    — Markdown summary
 *   action_items           json    — [{ description, assignee?, due_date? }]
 *   summary_status         enum    — pending | generating | complete | failed
 *   summary_generated_at   datetime
 *   summary_error          string
 *
 * Run:
 *   pnpm tsx scripts/setup-meeting-transcript-fields.ts
 *
 * Idempotent: re-running is safe.
 */

import 'dotenv/config';

const DIRECTUS_URL = process.env.DIRECTUS_URL || 'http://localhost:8055';
const DIRECTUS_TOKEN = process.env.DIRECTUS_SERVER_TOKEN || process.env.DIRECTUS_ADMIN_TOKEN || '';

if (!DIRECTUS_TOKEN) {
	console.error('Error: DIRECTUS_SERVER_TOKEN or DIRECTUS_ADMIN_TOKEN environment variable is required');
	process.exit(1);
}

async function directusRequest<T = unknown>(
	path: string,
	method: 'GET' | 'POST' | 'PATCH' | 'DELETE' = 'GET',
	body?: unknown,
): Promise<{ data: T | null; error: string | null }> {
	try {
		const response = await fetch(`${DIRECTUS_URL}${path}`, {
			method,
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${DIRECTUS_TOKEN}`,
			},
			body: body ? JSON.stringify(body) : undefined,
		});

		const text = await response.text();
		if (!response.ok) {
			if (response.status === 409) return { data: null, error: 'already_exists' };
			if (response.status === 400 && /already exists|already has an associated/i.test(text)) {
				return { data: null, error: 'already_exists' };
			}
			return { data: null, error: `${response.status}: ${text}` };
		}

		const json = text ? JSON.parse(text) : {};
		return { data: json.data ?? null, error: null };
	} catch (err: any) {
		return { data: null, error: err.message };
	}
}

async function createField(collection: string, field: Record<string, any>) {
	console.log(`  Creating field: ${collection}.${field.field}`);
	const { error } = await directusRequest(`/fields/${collection}`, 'POST', field);
	if (error === 'already_exists' || error?.includes('already exists')) {
		console.log(`    -> Already exists, skipping`);
		return true;
	}
	if (error) {
		console.error(`    -> Error: ${error}`);
		return false;
	}
	console.log(`    -> Created`);
	return true;
}

async function setup() {
	console.log('\n=== video_meetings — transcript + summary fields ===');

	await createField('video_meetings', {
		field: 'transcript_id',
		type: 'string',
		meta: { interface: 'input', readonly: true, note: 'Daily.co transcript handle' },
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'transcript_url',
		type: 'string',
		meta: { interface: 'input', readonly: true, note: 'Daily-hosted transcript download URL' },
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'transcript_text',
		type: 'text',
		meta: {
			interface: 'input-multiline',
			readonly: true,
			note: 'Plain-text transcript with speaker labels',
		},
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'summary',
		type: 'text',
		meta: {
			interface: 'input-rich-text-md',
			note: 'Markdown summary generated by Earnest AI',
		},
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'action_items',
		type: 'json',
		meta: {
			interface: 'list',
			note: 'AI-extracted action items',
			options: {
				template: '{{ description }}',
				fields: [
					{
						field: 'description',
						name: 'Description',
						type: 'string',
						meta: { interface: 'input', required: true },
					},
					{
						field: 'assignee',
						name: 'Assignee',
						type: 'string',
						meta: { interface: 'input' },
					},
					{
						field: 'due_date',
						name: 'Due',
						type: 'date',
						meta: { interface: 'datetime' },
					},
				],
			},
		},
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'summary_status',
		type: 'string',
		meta: {
			interface: 'select-dropdown',
			options: {
				choices: [
					{ text: 'Pending', value: 'pending' },
					{ text: 'Generating', value: 'generating' },
					{ text: 'Complete', value: 'complete' },
					{ text: 'Failed', value: 'failed' },
				],
			},
			note: 'AI summary lifecycle',
		},
		schema: { is_nullable: true, default_value: 'pending' },
	});

	await createField('video_meetings', {
		field: 'summary_generated_at',
		type: 'timestamp',
		meta: { interface: 'datetime', readonly: true },
		schema: { is_nullable: true },
	});

	await createField('video_meetings', {
		field: 'summary_error',
		type: 'string',
		meta: { interface: 'input', readonly: true, note: 'Last failure message, if any' },
		schema: { is_nullable: true },
	});
}

async function main() {
	console.log('==========================================');
	console.log('  Meeting Transcript + Summary — Schema Setup');
	console.log('==========================================');
	console.log(`Directus URL: ${DIRECTUS_URL}`);
	console.log('');

	await setup();

	console.log('');
	console.log('==========================================');
	console.log('  Done');
	console.log('==========================================');
	console.log('Next: run setup-webhook to subscribe to transcript.ready-to-download.');
}

main().catch((err) => {
	console.error('Fatal:', err);
	process.exit(1);
});
