// server/utils/web-push.ts
// Centralized web-push config + per-user send helper.
//
// Phase 5 (Web Push). VAPID keys come from env (generated by
// scripts/setup-push-subscriptions.ts). Send-side is fire-and-forget —
// callers never block on push delivery. 410 Gone (subscription expired or
// unsubscribed) removes the row so the next send doesn't bounce.

import webpush from 'web-push'
import { deleteItem, readItems, updateItem } from '@directus/sdk'

let configured = false

function ensureConfigured(): boolean {
	if (configured) return true
	const config = useRuntimeConfig()
	const publicKey = config.public?.vapidPublicKey
	const privateKey = (config as any).vapidPrivateKey
	const subject = (config as any).vapidSubject || 'mailto:peter@huestudios.com'
	if (!publicKey || !privateKey) {
		// First call without keys configured — log once and return false. The
		// send-side wraps this and silently no-ops so dev environments without
		// VAPID keys don't spam errors.
		console.warn('[web-push] VAPID keys not configured — skipping push delivery')
		return false
	}
	webpush.setVapidDetails(subject, publicKey, privateKey)
	configured = true
	return true
}

export interface PushSubscriptionRow {
	id: string
	user: string
	origin: string
	endpoint: string
	p256dh: string
	auth: string
}

export interface PushPayload {
	title: string
	body?: string
	url?: string
	tag?: string
	icon?: string
	badge?: string
	/** Free-form metadata surfaced to the SW (e.g. for analytics). */
	data?: Record<string, any>
}

/**
 * Send a push to every subscription belonging to a recipient. Fire-and-forget
 * — callers should not await this in a request-blocking path. Returns void
 * once the dispatch promises are scheduled.
 *
 * Failures per-subscription are logged but don't reject. 410 Gone responses
 * delete the corresponding push_subscriptions row.
 */
export async function pushToUser(recipientId: string, payload: PushPayload): Promise<void> {
	if (!ensureConfigured()) return
	if (!recipientId) return

	const directus = getServerDirectus()
	let subs: PushSubscriptionRow[] = []
	try {
		subs = (await directus.request(
			readItems('push_subscriptions' as any, {
				filter: { user: { _eq: recipientId } } as any,
				fields: ['id', 'user', 'origin', 'endpoint', 'p256dh', 'auth'] as any,
				limit: -1,
			} as any),
		)) as any
	} catch (err) {
		console.error('[web-push] failed to load subscriptions for', recipientId, err)
		return
	}
	if (!subs.length) return

	const body = JSON.stringify(payload)

	// Don't await individual sends — schedule them all in parallel and let
	// failures resolve asynchronously. The caller's request returns
	// immediately.
	void Promise.allSettled(
		subs.map(async (sub) => {
			try {
				await webpush.sendNotification(
					{ endpoint: sub.endpoint, keys: { p256dh: sub.p256dh, auth: sub.auth } },
					body,
					{ TTL: 60 * 60 * 24 }, // 24h — fine for "you have an update" UX
				)
				// Best-effort last_seen_at bump so we can age out cold subscriptions later.
				try {
					await directus.request(
						updateItem('push_subscriptions' as any, sub.id, {
							last_seen_at: new Date().toISOString(),
						} as any),
					)
				} catch {
					// Non-fatal — the row stays usable even without the timestamp.
				}
			} catch (err: any) {
				const status = err?.statusCode || err?.status
				if (status === 404 || status === 410) {
					// Subscription is gone — clean it up so the next send doesn't bounce.
					try {
						await directus.request(deleteItem('push_subscriptions' as any, sub.id))
					} catch (cleanupErr) {
						console.error('[web-push] failed to clean up stale sub', sub.id, cleanupErr)
					}
					return
				}
				console.error('[web-push] send failed for', sub.endpoint, status, err?.body || err?.message || err)
			}
		}),
	)
}

/**
 * Convenience for routes that want to push to many users at once.
 */
export async function pushToUsers(recipientIds: string[], payload: PushPayload): Promise<void> {
	const unique = Array.from(new Set(recipientIds.filter(Boolean)))
	await Promise.all(unique.map((id) => pushToUser(id, payload)))
}
